/* HeRo — Guia de Viagens
 * Cidade: Doha, Catar · Roteiro: setembro/2026
 *
 * REGRA DE OURO DESTE ARQUIVO: nada de preço inventado.
 * precoNota === 'confirmado'  -> valor veio de fonte citada em `fontes`
 * precoNota === 'nao-confirmado' -> faixa é ESTIMATIVA declarada, nunca apresentar como preço oficial
 *
 * Coordenadas: aproximadas, no nível do quarteirão/distrito. Servem para ordenar
 * por proximidade. Para navegar, use sempre `mapsQuery` (busca pelo nome).
 */

const HERO_CIDADE = {
  id: 'doha-2026-09',
  cidade: 'Doha',
  pais: 'Catar',
  periodo: 'Setembro de 2026',
  pesquisadoEm: '2026-09-11',
  base: {
    nome: 'Souq Waqif Boutique Hotels by Tivoli',
    lat: 25.2867, lng: 51.5333,
    mapsQuery: 'Souq Waqif Boutique Hotels by Tivoli, Doha'
  },
  cambio: {
    par: 'QAR/BRL',
    valor: 1.40,
    data: '2026-09-11',
    metodo: 'QAR tem paridade fixa com o dólar (3,64 QAR = 1 USD). Com USD/BRL ~5,10, ' +
            'chega-se a 1 QAR = R$ 1,40. Conferido contra XE (1,3988) e média de 7 dias (1,4172).',
    fontes: [
      { t: 'XE — QAR/BRL', u: 'https://www.xe.com/currencyconverter/convert/?Amount=1&From=QAR&To=BRL' },
      { t: 'Wise — QAR/BRL', u: 'https://wise.com/gb/currency-converter/qar-to-brl-rate' },
      { t: 'Investing — USD/BRL', u: 'https://br.investing.com/currencies/usd-brl' }
    ]
  }
};

/* Atalhos de fonte reaproveitados */
const F = {
  michelin26: { t: 'MICHELIN Guide Doha 2026 — lista completa', u: 'https://guide.michelin.com/qa/en/article/michelin-guide-ceremony/full-list-michelin-guide-doha-selection' },
  michelinQa: { t: 'MICHELIN Guide — Qatar', u: 'https://guide.michelin.com/en/qa/restaurants' },
  michelinLocal: { t: 'MICHELIN — Eat Like a Local: Doha’s Homegrown Heroes', u: 'https://guide.michelin.com/qa/en/article/dining-out/discover-doha-local-michelin-eats' },
  michelinQatari: { t: 'MICHELIN — Qatari Dishes and Where to Find Them', u: 'https://guide.michelin.com/qa/en/article/dining-out/where-to-find-qatari-dishes-doha' },
  michelinSouq: { t: 'MICHELIN — Best Restaurants Near Souq Waqif', u: 'https://guide.michelin.com/qa/en/best-of/best-restaurants-near-souq-waqif-doha' },
  visitQatar: { t: 'Visit Qatar — Dining', u: 'https://visitqatar.com/intl-en/things-to-do/dining' },
  qm: { t: 'Qatar Museums — Restaurants & Cafés', u: 'https://qm.org.qa/en/visit/restaurants-and-cafes/' },
  tivoli: { t: 'Souq Waqif Boutique Hotels by Tivoli — Restaurantes', u: 'https://www.tivolihotels.com/en/souq-waqif-doha/restaurants' },
  alcool: { t: 'Regras de álcool no Catar (2026)', u: 'https://experiencedoha.com/blog/alcohol-guide-doha' }
};

const HERO_RESTAURANTES = [

/* ============================================================
   1. DENTRO / COLADO NO SOUQ WAQIF  — caminhada a partir do hotel
   ============================================================ */
{
  id: 'argan',
  nome: 'Argan',
  status: 'aberto',
  statusNota: 'MICHELIN Bib Gourmand, mantido na edição Doha 2026. Aberto 12h30–23h30.',
  cozinha: 'Marroquina',
  categorias: ['arabe', 'alta-acessivel'],
  destaque: 'BIB GOURMAND · dentro do seu hotel',
  local: 'Souq Waqif Boutique Hotels by Tivoli — Al Jasra St',
  bairro: 'Souq Waqif',
  lat: 25.2869, lng: 51.5330,
  mapsQuery: 'Argan Moroccan Restaurant Souq Waqif Doha',
  distKm: 0.1, tempoMin: 1, aPe: true,
  precoQar: [140, 240],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Faixa estimada a partir do posicionamento Bib Gourmand (cozinha de qualidade a preço moderado). Cardápio com preços não acessível publicamente.',
  degustacao: null,
  brunch: null,
  almoco: { desc: 'À la carte a partir das 12h30', qar: null },
  alcool: false,
  alcoolNota: 'Souq Waqif é área seca. O Tivoli não serve álcool.',
  reserva: 'recomendavel',
  ambiente: ['tradicional', 'romântico', 'sofisticado-discreto'],
  vista: 'Rua pedestre do Souq, pátio marroquino',
  rede: 'local',
  notas: { gastro: 8.5, autent: 7.5, custo: 9.0, doha: 9.0 },
  pratos: [
    { nome: 'Tagine de cordeiro', qar: null, porque: 'A especialidade da casa segundo o MICHELIN — tagine e cuscuz são o que o guia cita nominalmente.' },
    { nome: 'Cuscuz (vegetariano ou de carnes)', qar: null, porque: 'O outro prato que o MICHELIN destaca. Cuscuz marroquino de verdade é raro no Brasil.' },
    { nome: 'Harira', qar: null, porque: 'Sopa marroquina de grão-de-bico e tomate; abre bem a refeição e mostra o tempero da casa.' },
    { nome: 'Pastilla', qar: null, porque: 'Doce-salgado com canela — o prato que mais divide e mais marca numa mesa de casal.' }
  ],
  porque: 'É a melhor relação esforço/retorno da viagem inteira: você desce do quarto e come num Bib Gourmand do MICHELIN. Marroquino não é qatari, mas é a cozinha árabe mais elaborada disponível a pé do Souq — e não há filial disso no Brasil.',
  tel: '+97444336872',
  site: 'https://www.tivolihotels.com/en/souq-waqif-doha/restaurants/argan',
  reservaUrl: 'https://www.tivolihotels.com/en/souq-waqif-doha/restaurants/argan',
  fontes: [F.tivoli, F.michelinSouq, { t: 'MICHELIN — Argan', u: 'https://guide.michelin.com/en/doha-region/doha_2433318/restaurant/argan' }, { t: 'Marhaba — Argan recebe Bib Gourmand', u: 'https://marhaba.qa/argan-restaurant-at-souq-waqif-boutique-hotels-awarded-michelin-bib-gourmand-2025/' }]
},
{
  id: 'shay-al-shomous',
  nome: 'Shay Al Shomous',
  status: 'aberto',
  statusNota: 'Em operação desde 2014, tocado pela própria dona. Citado pelo MICHELIN como endereço de madrouba.',
  cozinha: 'Qatari tradicional (café da manhã)',
  categorias: ['qatari', 'local', 'cafe'],
  destaque: 'O café da manhã qatari',
  local: 'Souq Waqif (canto junto ao Al Bidda Boutique Hotel)',
  bairro: 'Souq Waqif',
  lat: 25.2874, lng: 51.5344,
  mapsQuery: 'Shay Al Shomous Souq Waqif Doha',
  distKm: 0.3, tempoMin: 4, aPe: true,
  precoQar: [30, 70],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Faixa estimada de café da manhã popular. Sem cardápio com preços publicado.',
  degustacao: null, brunch: null,
  almoco: { desc: 'Foco em café da manhã; funciona pela manhã e início da tarde', qar: null },
  alcool: false,
  reserva: 'nao',
  ambiente: ['casual', 'tradicional', 'popular'],
  vista: 'Beco do Souq',
  rede: 'local',
  notas: { gastro: 7.0, autent: 10, custo: 10, doha: 9.5 },
  pratos: [
    { nome: 'Balaleet', qar: null, porque: 'Aletria doce com açafrão e cardamomo coberta por omelete. É o café da manhã do Golfo — não existe equivalente no Brasil.' },
    { nome: 'Madrouba', qar: null, porque: 'O MICHELIN aponta esta casa como um dos melhores endereços de madrouba de Doha. Arroz batido com frango, textura de mingau salgado.' },
    { nome: 'Khobiz regag', qar: null, porque: 'Pão finíssimo feito na chapa na sua frente, com queijo e mel ou ovo. É o teatro da casa.' },
    { nome: 'Baid o tomate', qar: null, porque: 'Ovos com tomate; o prato mais simples e o melhor termômetro do tempero da cozinha.' },
    { nome: 'Karak', qar: null, porque: 'O chá nacional. Pedir aqui é obrigatório.' }
  ],
  porque: 'Dona Shams Al Qassabi abriu isso em 2014 e virou símbolo da independência financeira das mulheres qataris. Você come comida qatari de casa, feita por qatari, no Souq — a 4 minutos a pé do hotel. É o oposto exato de restaurante de hotel.',
  tel: null,
  site: null,
  reservaUrl: null,
  fontes: [F.michelinQatari, { t: 'Al Jazeera — Sunshine for breakfast in Doha’s Souq Waqif', u: 'https://www.aljazeera.com/features/longform/2022/10/17/sunshine-for-breakfast-a-chat-with-qatars-iconic-shomous' }, { t: 'Discover Qatar — Seasoned With Tradition', u: 'https://www.discoverqatar.qa/travel-journal/seasoned-with-tradition/' }]
},
{
  id: 'bandar-aden',
  nome: 'Bandar Aden',
  status: 'aberto',
  statusNota: 'Casa tradicional do Souq, site próprio ativo.',
  cozinha: 'Iemenita',
  categorias: ['arabe', 'local'],
  destaque: 'Mandi no chão, sobre tapete',
  local: 'Souq Waqif — borda norte, de frente para o parque/Corniche',
  bairro: 'Souq Waqif',
  lat: 25.2879, lng: 51.5329,
  mapsQuery: 'Bandar Aden Restaurant Souq Waqif Doha',
  distKm: 0.25, tempoMin: 3, aPe: true,
  precoQar: [50, 110],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Estimativa. As fontes convergem em "porções generosas e preços acessíveis", sem valores publicados.',
  degustacao: null, brunch: null,
  almoco: { desc: 'Almoço é o horário forte do mandi', qar: null },
  alcool: false,
  reserva: 'recomendavel',
  reservaNota: 'Enche muito. Chegue cedo ou reserve.',
  ambiente: ['casual', 'tradicional', 'animado', 'família'],
  vista: 'Parque do Souq',
  rede: 'local',
  notas: { gastro: 8.0, autent: 9.5, custo: 9.5, doha: 8.5 },
  pratos: [
    { nome: 'Lamb Mandi', qar: null, porque: 'O carro-chefe. Cordeiro cozido lentamente em forno subterrâneo sobre arroz aromático. A carne desfia sozinha.' },
    { nome: 'Haneeth / "buried meat"', qar: null, porque: 'A versão "enterrada" — mais seca, mais concentrada. Quem já comeu mandi deve pedir esta.' },
    { nome: 'Pão iemenita fresco', qar: null, porque: 'Citado por praticamente toda fonte como excepcional. Sai do forno na hora.' },
    { nome: 'Chicken Mandi', qar: null, porque: 'Alternativa mais leve, mesmo arroz.' }
  ],
  porque: 'Iemenita é a cozinha que os próprios moradores do Golfo procuram quando querem comer bem e barato. Sentar no chão sobre tapete e desfiar cordeiro com a mão é uma experiência cultural que nenhum restaurante de hotel entrega.',
  tel: null,
  site: 'http://www.bandaraden.com/',
  reservaUrl: null,
  fontes: [{ t: 'Bandar Aden — site oficial', u: 'http://www.bandaraden.com/' }, F.visitQatar]
},
{
  id: 'danat-al-bahar',
  nome: 'Danat Al Bahar BBQ Fish',
  status: 'aberto',
  statusNota: 'Site oficial ativo com reserva online. Filial do Souq (matriz em Al Wakrah, junto ao porto).',
  cozinha: 'Peixes e frutos do mar na brasa',
  categorias: ['peixe', 'local'],
  destaque: 'Escolha o peixe no gelo',
  local: 'Souq Waqif',
  bairro: 'Souq Waqif',
  lat: 25.2871, lng: 51.5338,
  mapsQuery: 'Danat Al Bahar BBQ Fish Souq Waqif Doha',
  distKm: 0.2, tempoMin: 3, aPe: true,
  precoQar: [50, 200],
  precoNota: 'parcial',
  precoDetalhe: 'Pratos principais QAR 80–200 conforme o peixe; refeição relatada em QAR 50–100 por pessoa. Peixe é vendido por quilo — o preço final depende da peça escolhida no balcão. Confirme o preço/kg ANTES de mandar grelhar.',
  degustacao: null, brunch: null,
  almoco: { desc: 'Almoço e jantar', qar: null },
  alcool: false,
  reserva: 'recomendavel',
  reservaNota: 'Tem reserva online no site oficial.',
  ambiente: ['casual', 'animado', 'família'],
  vista: 'Beco do Souq, mesas dentro e fora',
  rede: 'local',
  notas: { gastro: 8.0, autent: 9.0, custo: 9.0, doha: 8.5 },
  pratos: [
    { nome: 'Hamour na brasa', qar: null, porque: 'O peixe do Golfo por excelência (garoupa). Carne firme, ideal para a brasa.' },
    { nome: 'Sheri / seabream inteiro', qar: null, porque: 'Peixe local menor, mais barato e mais saboroso que o hamour para duas pessoas.' },
    { nome: 'Camarão grelhado', qar: null, porque: 'Camarão do Golfo é doce e grande. Peça no alho.' },
    { nome: 'Arroz mandi como acompanhamento', qar: null, porque: 'A combinação local: peixe da brasa + arroz aromático.' }
  ],
  porque: 'É o melhor peixe do Souq e um dos melhores custo-benefício de Doha. O modelo "escolha no gelo e mande grelhar" é o que os locais fazem. Para um casal, um peixe inteiro de bom tamanho resolve a mesa.',
  tel: null,
  site: 'https://danatalbahar.com/',
  reservaUrl: 'https://danatalbahar.com/reserve',
  fontes: [{ t: 'Danat Al Bahar — site oficial (menu)', u: 'https://danatalbahar.com/menu' }, { t: 'Danat Al Bahar — reservas', u: 'https://danatalbahar.com/reserve' }]
},
{
  id: 'parisa',
  nome: 'Parisa Souq Waqif',
  status: 'aberto',
  cozinha: 'Persa',
  categorias: ['arabe', 'local', 'romantico'],
  destaque: 'O salão de espelhos',
  local: 'Souq Waqif — Al Ahmed St',
  bairro: 'Souq Waqif',
  lat: 25.2866, lng: 51.5341,
  mapsQuery: 'Parisa Souq Waqif Doha',
  distKm: 0.2, tempoMin: 3, aPe: true,
  precoQar: [120, 220],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Estimativa para jantar persa completo a dois no Souq. Sem tabela pública.',
  degustacao: null, brunch: null,
  almoco: { desc: 'Almoço e jantar', qar: null },
  alcool: false,
  reserva: 'recomendavel',
  ambiente: ['romântico', 'espetacular', 'tradicional'],
  vista: 'Interior de mosaicos e milhares de espelhos montados ao longo de 3,5 anos',
  rede: 'local',
  notas: { gastro: 7.5, autent: 7.5, custo: 8.0, doha: 9.0 },
  pratos: [
    { nome: 'Kashk-e Bademjan', qar: null, porque: 'Berinjela frita com nozes e kashk (iogurte seco). O melhor mezze persa e quase impossível de achar bem feito no Brasil.' },
    { nome: 'Koofteh Anar', qar: null, porque: 'Almôndegas em molho de romã. Doce-ácido, muito persa.' },
    { nome: 'Kebab com arroz de açafrão', qar: null, porque: 'O teste básico de uma casa persa: o arroz tem que vir soltinho, com a crosta.' },
    { nome: 'Faloudeh Shirazi', qar: null, porque: 'Sobremesa de aletria gelada com água de rosas e limão. Não existe nada parecido.' }
  ],
  porque: 'A comida é boa, não genial — mas o salão é uma das coisas mais bonitas de Doha, e você chega a pé. Para uma noite romântica sem sair do Souq, é imbatível visualmente. Vá pelo ambiente, peça os mezze.',
  tel: null,
  site: null,
  reservaUrl: null,
  fontes: [{ t: 'MICHELIN — melhores restaurantes perto do Souq Waqif', u: 'https://guide.michelin.com/qa/en/best-of/best-restaurants-near-souq-waqif-doha' }]
},
{
  id: 'abo-shariha',
  nome: 'Abo Shariha',
  status: 'aberto',
  cozinha: 'Árabe popular (jordaniana/palestina)',
  categorias: ['arabe', 'local', 'barato'],
  destaque: 'Almoço casual imbatível',
  local: 'Dentro do Souq Waqif',
  bairro: 'Souq Waqif',
  lat: 25.2864, lng: 51.5336,
  mapsQuery: 'Abo Shariha Restaurant Souq Waqif Doha',
  distKm: 0.2, tempoMin: 3, aPe: true,
  precoQar: [20, 50],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Estimativa de fast food árabe. Fontes convergem em "preço muito razoável".',
  degustacao: null, brunch: null,
  almoco: { desc: 'Balcão, o dia todo', qar: null },
  alcool: false,
  reserva: 'nao',
  ambiente: ['casual', 'balcão', 'popular'],
  vista: null,
  rede: 'local',
  notas: { gastro: 7.5, autent: 9.0, custo: 10, doha: 7.5 },
  pratos: [
    { nome: 'Falafel recheado', qar: null, porque: 'A especialidade citada nominalmente pelas fontes. Falafel com recheio dentro — versão levantina que não chegou ao Brasil.' },
    { nome: 'Homus', qar: null, porque: 'Repetidamente apontado como o melhor de Doha. Peça com azeite e pinoli.' },
    { nome: 'Shawarma no pão saj', qar: null, porque: 'Saj é o pão finíssimo assado em cúpula. Muda completamente o shawarma.' },
    { nome: 'Kaak', qar: null, porque: 'Pão de gergelim assado na casa.' }
  ],
  porque: 'É onde se almoça no Souq quando não se quer cerimônia: barato, rápido, muito bem feito. Casa antiga, aberta desde os anos 1950 segundo suas próprias fontes. O homus vale a visita sozinho.',
  tel: null, site: null, reservaUrl: null,
  fontes: [{ t: 'Visit Qatar — street food', u: 'https://visitqatar.com/intl-en/things-to-do/get-inspired/street-food' }]
},
{
  id: 'damasca-one',
  nome: 'Damasca One',
  status: 'aberto',
  cozinha: 'Síria',
  categorias: ['arabe', 'local'],
  local: 'Souq Waqif (junto ao Souq Waqif Park)',
  bairro: 'Souq Waqif',
  lat: 25.2877, lng: 51.5335,
  mapsQuery: 'Damasca One Restaurant Souq Waqif Doha',
  distKm: 0.25, tempoMin: 3, aPe: true,
  precoQar: [70, 140],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Estimativa. Cardápio disponível em plataformas de delivery, mas os preços de delivery não refletem o salão.',
  degustacao: null, brunch: null, almoco: { desc: 'Almoço e jantar', qar: null },
  alcool: false,
  reserva: 'recomendavel',
  ambiente: ['casual', 'animado', 'terraço'],
  vista: 'Mesas voltadas para o parque do Souq',
  rede: 'local',
  notas: { gastro: 7.5, autent: 8.5, custo: 8.5, doha: 7.5 },
  pratos: [
    { nome: 'Kebab damasceno', qar: null, porque: 'Cordeiro moído com salsa, cebola e especiarias de Damasco. É a assinatura da casa.' },
    { nome: 'Shaqqaf', qar: null, porque: 'Prato sírio de forno com berinjela e carne. Raro fora da Síria e do Levante.' },
    { nome: 'Costeletas de cordeiro', qar: null, porque: 'Marinadas em alho e azeite, grelhadas. Simples e certeiro.' },
    { nome: 'Mezze quente variado', qar: null, porque: 'Para casal, a melhor forma de comer aqui é fazer a refeição toda de mezze.' }
  ],
  porque: 'A alternativa síria ao iemenita do Bandar Aden, também dentro do Souq. Mesa ao ar livre voltada para o parque — bom para a noite quente de setembro, quando o Souq fica vivo depois das 20h.',
  tel: null, site: null, reservaUrl: null,
  fontes: [F.tivoli]
},
{
  id: 'al-aker',
  nome: 'Al Aker Sweets',
  status: 'aberto',
  cozinha: 'Doces árabes',
  categorias: ['doce', 'local', 'barato'],
  destaque: 'A melhor knafeh',
  local: 'Souq Waqif (e outras unidades: Pearl, Salwa Rd, Al Wakrah)',
  bairro: 'Souq Waqif',
  lat: 25.2870, lng: 51.5346,
  mapsQuery: 'Al Aker Sweets Souq Waqif Doha',
  distKm: 0.3, tempoMin: 4, aPe: true,
  precoQar: [20, 60],
  precoNota: 'parcial',
  precoDetalhe: 'Fonte relata ~QAR 50–60 para prato principal + sobremesa. Só a knafeh fica bem abaixo disso.',
  degustacao: null, brunch: null, almoco: null,
  alcool: false,
  reserva: 'nao',
  ambiente: ['casual', 'balcão'],
  vista: null,
  rede: 'regional',
  notas: { gastro: 8.0, autent: 9.0, custo: 10, doha: 8.0 },
  pratos: [
    { nome: 'Knafeh nabulsieh', qar: null, porque: 'Queijo derretido sob massa kadaif crocante e calda de açúcar. Servida quente, na hora. É a melhor sobremesa acessível de Doha.' }
  ],
  porque: 'Sobremesa de verdade depois do jantar no Souq. Peça uma porção para dividir e coma em pé — é assim que se faz.',
  tel: null, site: null, reservaUrl: null,
  fontes: [{ t: 'Mandarin Oriental — guia essencial de Doha', u: 'https://www.mandarinoriental.com/en/unfold-magazine/destinations/essential-guide/doha' }]
},

/* ============================================================
   2. MSHEIREB / MIA / NMoQ — 5 a 8 min de carro
   ============================================================ */
{
  id: 'idam',
  nome: 'IDAM by Alain Ducasse',
  status: 'aberto',
  statusNota: 'REABRIU EM 3 DE SETEMBRO DE 2026 após a pausa de verão. Mantém 1 estrela MICHELIN em 2026.',
  cozinha: 'Francesa contemporânea com sotaque árabe',
  categorias: ['alta', 'internacional'],
  destaque: '★ MICHELIN · reabertura 03/09/2026',
  local: 'Museum of Islamic Art — último andar',
  bairro: 'MIA / Corniche Sul',
  lat: 25.2953, lng: 51.5397,
  mapsQuery: 'IDAM by Alain Ducasse Museum of Islamic Art Doha',
  distKm: 1.6, tempoMin: 6,
  precoQar: [560, 690],
  precoNota: 'parcial',
  precoDetalhe: 'QAR 560 (6 tempos, almoço ou jantar) e QAR 690 (8 tempos, só jantar) são os valores do "Experience Menu" divulgados antes da reabertura. O novo menu "Ember & Tide" (4 tempos no almoço / 8 tempos no jantar) foi anunciado SEM preço. Confirme no ato da reserva.',
  degustacao: { nome: 'Ember & Tide — 8 tempos (jantar)', qar: 690, confirmado: false },
  brunch: null,
  almoco: { desc: 'Ember & Tide — 4 tempos', qar: null },
  alcool: true,
  alcoolNota: 'Sim. É um dos poucos endereços de alta gastronomia fora de hotel com licença.',
  reserva: 'obrigatoria',
  ambiente: ['sofisticado', 'romântico', 'vista'],
  vista: 'A melhor de Doha: o skyline de West Bay do alto do museu de I. M. Pei, sobre a baía',
  rede: 'internacional',
  redeNota: 'Marca Ducasse, mas ESTA casa é única: existe só em Doha, dentro do MIA, com cozinha desenhada para o lugar.',
  notas: { gastro: 9.5, autent: 6.5, custo: 6.0, doha: 9.5 },
  pratos: [
    { nome: 'Olhete (amberjack) na brasa, cime di rapa, bottarga, molho marinière', qar: null, porque: 'Abertura do menu novo de setembro/2026. Peixe do Golfo tratado com técnica francesa.' },
    { nome: 'Wagyu selado, chalota confitada, jus de bacon de camelo, groselha-preta', qar: null, porque: 'Bacon de camelo. É exatamente o tipo de prato que só faz sentido em Doha e em nenhum outro Ducasse do mundo.' },
    { nome: 'Carabineros com sabugueiro, enguia grelhada e granité de yuzu', qar: null, porque: 'O prato mais técnico da carta atual.' },
    { nome: 'Rodovalho levemente defumado, caviar Kristal, "foie gras" marinho, vinagrete de kombu', qar: null, porque: 'O prato de assinatura do menu de 8 tempos.' }
  ],
  porque: 'É a alta gastronomia com maior razão de existir em Doha: estrela MICHELIN, cozinha que usa ingredientes do Golfo (bacon de camelo, peixe local), dentro do prédio mais bonito do país, a 6 minutos do seu hotel. Reabriu há oito dias — o menu está novo.',
  tel: '+97444224488',
  site: 'https://idam.com/',
  reservaUrl: 'https://idam.com/',
  fontes: [F.michelin26, { t: 'Qatar Museums — reabertura do IDAM', u: 'https://qm.org.qa/en/press/press-releases/in-q-announces-reopening-of-idam-at-museum-of-islamic-art/' }, { t: 'Gulf Times — reabertura do IDAM', u: 'https://www.gulf-times.com/story/728315/IN-Q-announces-reopening-of-IDAM-at-Museum-of-Islamic-Art' }, { t: 'Time Out Doha — restaurantes do Qatar Museums reabrem', u: 'https://www.timeoutdoha.com/food-drink/food-news/qatar-museums-restaurants-reopen' }, { t: 'IDAM — cardápio oficial', u: 'https://idam.com/cuisine' }]
},
{
  id: 'jiwan',
  nome: 'Jiwan',
  status: 'aberto',
  statusNota: 'CONFIRMADO: reabriu em 30 DE AGOSTO DE 2026 com cardápio novo de estação. Bib Gourmand MICHELIN 2026.',
  cozinha: 'Qatari/árabe contemporânea',
  categorias: ['qatari', 'alta', 'arabe'],
  destaque: 'BIB GOURMAND · reabriu 30/08/2026',
  local: 'Museu Nacional do Catar (NMoQ) — 4º andar',
  bairro: 'NMoQ / Corniche Sul',
  lat: 25.2870, lng: 51.5514,
  mapsQuery: 'Jiwan Restaurant National Museum of Qatar Doha',
  distKm: 2.6, tempoMin: 8,
  precoQar: [300, 300],
  precoNota: 'confirmado',
  precoDetalhe: 'Menu-degustação a QAR 300 por pessoa, incluindo mocktails, bebidas quentes e água. Há também à la carte. Sunset Tea a QAR 100 por pessoa, das 15h30 às 18h30.',
  degustacao: { nome: 'Set menu (inclui bebidas não alcoólicas)', qar: 300, confirmado: true },
  brunch: null,
  almoco: { desc: 'À la carte e set menu; Sunset Tea 15h30–18h30', qar: 100 },
  alcool: false,
  alcoolNota: 'Restaurante de museu público — não serve álcool.',
  reserva: 'obrigatoria',
  reservaNota: 'jiwan.qa ou +974 4452 5725',
  ambiente: ['sofisticado', 'romântico', 'vista', 'design'],
  vista: 'Baía de Doha e o skyline, do alto do museu de Jean Nouvel',
  rede: 'local',
  notas: { gastro: 9.0, autent: 9.5, custo: 8.5, doha: 10 },
  pratos: [
    { nome: 'Olhete com cítricos e tahine', qar: null, porque: 'Entrada do cardápio novo de setembro/2026. Peixe cru do Golfo com tahine — a ideia central da casa em um prato.' },
    { nome: 'Paleta de cordeiro de 12 horas, hortelã e melaço de romã', qar: null, porque: 'O prato principal da estação atual, servido para a mesa dividir. É machboos repensado.' },
    { nome: 'Date mahalabia com pimenta e água de rosas', qar: null, porque: 'Pudim de tâmara com pimenta. A sobremesa assinatura e o prato mais citado da casa.' },
    { nome: 'Sunset Tea (QAR 100)', qar: 100, porque: 'Se o jantar não couber: chá da tarde com a mesma vista, por um terço do preço.' }
  ],
  porque: 'É o melhor argumento gastronômico do Catar sobre si mesmo: cozinha qatari e do Golfo levada a sério, feita para dividir, no museu que conta a história do país, com vista para a baía. Bib Gourmand significa que o MICHELIN considera isso barato para o que entrega — e a QAR 300 com bebidas incluídas, é.',
  tel: '+97444525725',
  site: 'https://jiwan.qa/',
  reservaUrl: 'https://jiwan.qa/',
  fontes: [F.michelin26, { t: 'Qatar Museums — Jiwan', u: 'https://qm.org.qa/en/press/press-releases/jiwan-welcomes-guests-from-around-the-world-to-savour-the-authentic-taste-of-qatar/' }, { t: 'NMoQ — Jiwan (oficial)', u: 'https://nmoq.org.qa/en/visit/jiwan/' }, { t: 'Time Out Doha — reabertura set/2026', u: 'https://www.timeoutdoha.com/food-drink/food-news/qatar-museums-restaurants-reopen' }, { t: 'Marhaba — novos menus de estação', u: 'https://marhaba.qa/qatar-museums-restaurants-launch-new-seasonal-menus/' }]
},
{
  id: 'bayt-sharq',
  nome: 'Bayt Sharq',
  status: 'aberto',
  statusNota: 'MICHELIN Selected. Mais de uma década em operação.',
  cozinha: 'Qatari e Oriente Médio tradicional',
  categorias: ['qatari', 'arabe', 'local'],
  destaque: 'MICHELIN Selected · casa histórica',
  local: 'Barahat Msheireb — casa Al Khulaifi restaurada, com museu próprio',
  bairro: 'Msheireb',
  lat: 25.2882, lng: 51.5267,
  mapsQuery: 'Bayt Sharq Msheireb Doha',
  distKm: 1.0, tempoMin: 5,
  precoQar: [120, 240],
  precoNota: 'parcial',
  precoDetalhe: 'Relatos convergentes: ~QAR 120 por pessoa à la carte; sets de café da manhã em torno de QAR 240; consumo mínimo relatado de ~QAR 180 para biryani/majboos; almoço em torno de QAR 200/pessoa. Não há tabela oficial publicada — trate como faixa, não como preço.',
  degustacao: null,
  brunch: { desc: 'Café da manhã qatari (balaleet, fígado de cordeiro, nakhi, bajella) ou "maalem" (falafel, foul, labneh, fatayer de zaatar)', qar: 240, confirmado: false },
  almoco: { desc: 'Machboos, madrouba, harees', qar: null },
  alcool: false,
  reserva: 'recomendavel',
  ambiente: ['tradicional', 'romântico', 'jardim', 'histórico'],
  vista: 'Casa de 100 anos com pátio, jardim, varanda e cabanas',
  rede: 'local',
  notas: { gastro: 8.5, autent: 9.5, custo: 7.5, doha: 9.5 },
  pratos: [
    { nome: 'Machboos de cordeiro', qar: null, porque: 'O MICHELIN cita esta casa nominalmente como a referência clássica de machboos em Doha. É o prato nacional.' },
    { nome: 'Madrouba', qar: null, porque: 'Arroz batido com frango até virar creme. Comida de casa qatari.' },
    { nome: 'Harees', qar: null, porque: 'Trigo e carne pilados juntos por horas. Prato de Ramadã, textura única.' },
    { nome: 'Balaleet (no café da manhã)', qar: null, porque: 'Doce e salgado ao mesmo tempo — o prato que melhor explica o paladar do Golfo.' },
    { nome: 'Mahalabia de açafrão', qar: null, porque: 'Sobremesa de leite com açafrão. Fecha a refeição do jeito certo.' }
  ],
  porque: 'Se você só vai comer qatari uma vez com garfo e faca num lugar bonito, é aqui ou no Jiwan. Bayt Sharq é o lado tradicional: casa de família de 100 anos com museu dentro, machboos clássico, jardim. O Jiwan é o lado contemporâneo.',
  tel: '+97455197131',
  site: null,
  reservaUrl: null,
  fontes: [F.michelinQatari, F.michelinLocal, { t: 'MICHELIN — Bayt Sharq', u: 'https://guide.michelin.com/us/en/doha-region/doha_2433318/restaurant/bayt-sharq' }]
},
{
  id: 'saasna',
  nome: 'Saasna',
  status: 'aberto',
  statusNota: 'MICHELIN Selected na edição 2026.',
  cozinha: 'Qatari contemporânea',
  categorias: ['qatari', 'local'],
  destaque: 'MICHELIN Selected',
  local: 'Msheireb Downtown Doha',
  bairro: 'Msheireb',
  lat: 25.2875, lng: 51.5258,
  mapsQuery: 'Saasna Restaurant Msheireb Downtown Doha',
  distKm: 1.1, tempoMin: 5,
  precoQar: [100, 200],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Estimativa. Sem tabela pública.',
  degustacao: null, brunch: null, almoco: { desc: 'Almoço e jantar', qar: null },
  alcool: false,
  reserva: 'recomendavel',
  ambiente: ['sofisticado', 'moderno', 'tradicional'],
  vista: null,
  rede: 'local',
  notas: { gastro: 8.5, autent: 9.5, custo: 8.0, doha: 9.0 },
  pratos: [
    { nome: 'Machboos de frutos do mar (hammour e camarão)', qar: null, porque: 'O MICHELIN destaca justamente esta versão: machboos que celebra a identidade costeira do Catar em vez da carne. É a diferença entre Saasna e Bayt Sharq.' },
    { nome: 'Salada Saasna', qar: null, porque: 'Citada pelo guia entre as recomendações da casa.' },
    { nome: 'Samosa', qar: null, porque: 'Entrada recomendada pelo MICHELIN.' },
    { nome: 'Sorvete de tâmara', qar: null, porque: 'A sobremesa da casa segundo o guia.' }
  ],
  porque: '"Saasna" significa "nossas raízes". Nasceu do livro de receitas da falecida Sheikha Ahmed Al Meer e é o projeto mais deliberado de traduzir a cozinha qatari para o século XXI. Se você já vai a Msheireb, é uma alternativa ao Bayt Sharq com viés costeiro.',
  tel: null,
  site: 'https://www.alsraiyahospitality.com/en/saasna',
  reservaUrl: null,
  fontes: [F.michelinQatari, { t: 'MICHELIN — Saasna', u: 'https://guide.michelin.com/us/en/doha-region/doha_2433318/restaurant/saasna' }, { t: 'Al Sraiya Hospitality — Saasna (oficial)', u: 'https://www.alsraiyahospitality.com/en/saasna' }]
},
{
  id: 'sawa',
  nome: 'SAWA by Sanad',
  status: 'aberto',
  statusNota: 'MICHELIN Selected. Fica no 1º andar de um clube privado, mas NÃO é preciso ser sócio para comer.',
  cozinha: 'Levantina contemporânea',
  categorias: ['arabe', 'alta'],
  destaque: 'MICHELIN Selected · hidden gem',
  local: 'Wadi Msheireb St, Msheireb Downtown',
  bairro: 'Msheireb',
  lat: 25.2870, lng: 51.5262,
  mapsQuery: 'SAWA by Sanad Msheireb Doha',
  distKm: 1.1, tempoMin: 5,
  precoQar: [180, 320],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Estimativa para jantar levantino contemporâneo com serviço de carrinho. Sem tabela pública.',
  degustacao: null, brunch: null, almoco: { desc: 'Almoço mais simples; o jantar é a versão completa', qar: null },
  alcool: false,
  reserva: 'obrigatoria',
  reservaNota: 'Clube privado — reserve antes, mesmo não sendo sócio.',
  ambiente: ['sofisticado', 'romântico', 'discreto', 'chique'],
  vista: null,
  rede: 'local',
  notas: { gastro: 8.5, autent: 8.5, custo: 7.5, doha: 8.5 },
  pratos: [
    { nome: 'Maqlooba palestina de cordeiro', qar: null, porque: 'O prato "de cabeça para baixo" — arroz, berinjela e cordeiro virados na mesa. Teatro e técnica.' },
    { nome: 'Frango zaatar', qar: null, porque: 'Clássico levantino que o guia cita como acerto da casa.' },
    { nome: 'Bolinhas de madrouba', qar: null, porque: 'Invenção da casa: transforma o mingau qatari em croquete. É o prato que mostra o que a cozinha está tentando fazer.' },
    { nome: 'Pratos do carrinho (só no jantar)', qar: null, porque: 'À noite a casa sobe o nível e serve do carrinho — vá jantar, não almoçar.' }
  ],
  porque: 'É o hidden gem mais defensável da lista: MICHELIN Selected, escondido dentro de um clube privado que quase nenhum turista acha, com cozinha levantina moderna de verdade. A 5 minutos do Souq.',
  tel: null,
  site: 'https://sanaddoha.com/en/home-en/',
  reservaUrl: 'https://www.opentable.com/r/sawa-by-sanad-doha',
  fontes: [F.michelinSouq, { t: 'MICHELIN — SAWA by Sanad', u: 'https://guide.michelin.com/en/doha-region/doha_2433318/restaurant/sawa-by-sanad' }]
},
{
  id: 'hoppers',
  nome: 'Hoppers',
  status: 'aberto',
  statusNota: 'MICHELIN Bib Gourmand 2026. Primeira casa do grupo londrino fora do Reino Unido.',
  cozinha: 'Sri Lanka e Sul da Índia',
  categorias: ['internacional', 'alta-acessivel'],
  destaque: 'BIB GOURMAND',
  local: 'Msheireb Downtown Doha',
  bairro: 'Msheireb',
  lat: 25.2868, lng: 51.5255,
  mapsQuery: 'Hoppers Doha Msheireb',
  distKm: 1.1, tempoMin: 5,
  precoQar: [110, 200],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Estimativa a partir do posicionamento Bib Gourmand.',
  degustacao: null, brunch: null, almoco: { desc: 'Almoço e jantar', qar: null },
  alcool: false,
  reserva: 'recomendavel',
  ambiente: ['casual', 'animado', 'moderno'],
  vista: null,
  rede: 'internacional',
  redeNota: 'Grupo JKS/Londres. Mas é a única unidade fora do Reino Unido — não dá para comer em Paris ou Dubai.',
  notas: { gastro: 8.5, autent: 5.0, custo: 8.5, doha: 6.5 },
  pratos: [
    { nome: 'Egg hopper', qar: null, porque: 'A panqueca côncava de farinha de arroz e leite de coco com ovo no centro. É o prato que dá nome à casa.' },
    { nome: 'Dosa', qar: null, porque: 'Crepe fermentado do sul da Índia. Aqui é feito a sério.' },
    { nome: 'Curry de caranguejo', qar: null, porque: 'O prato mais famoso da casa em Londres.' },
    { nome: 'Sambols', qar: null, porque: 'Os condimentos cingaleses — coco, cebola, pimenta. Metade da graça da comida está neles.' }
  ],
  porque: 'Excelente comida, mas responda com honestidade: você vai a Doha para comer cingalês? Só entra no roteiro se sobrar noite ou se for almoço. A vantagem é que é a única unidade do mundo fora de Londres.',
  tel: null,
  site: 'https://www.alsraiyahospitality.com/en/hoppers',
  reservaUrl: null,
  fontes: [F.michelin26, { t: 'MICHELIN — Hoppers', u: 'https://guide.michelin.com/us/en/doha-region/doha_2433318/restaurant/hoppers-1206059' }]
},
{
  id: 'gahwetna',
  nome: 'Gahwetna',
  status: 'aberto',
  cozinha: 'Café qatari / khaleeji',
  categorias: ['cafe', 'qatari', 'local', 'barato'],
  destaque: 'Karak e comida de casa',
  local: 'Barahat Msheireb, Sikkat Al Maiz',
  bairro: 'Msheireb',
  lat: 25.2880, lng: 51.5270,
  mapsQuery: 'Gahwetna Qatar Msheireb Doha',
  distKm: 1.0, tempoMin: 5,
  precoQar: [25, 70],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Estimativa de café/refeição rápida. Fontes convergem em "preços acessíveis".',
  degustacao: null, brunch: null, almoco: { desc: 'Café da manhã, sanduíches e pratos rápidos o dia todo', qar: null },
  alcool: false,
  reserva: 'nao',
  ambiente: ['casual', 'tradicional', 'majlis'],
  vista: 'Decoração inspirada no souq, no coração pedestre de Msheireb',
  rede: 'local',
  notas: { gastro: 7.0, autent: 9.0, custo: 9.5, doha: 8.0 },
  pratos: [
    { nome: 'Karak', qar: null, porque: 'O chá nacional: leite condensado, cardamomo, fervido longo. Aqui é o motivo da casa existir.' },
    { nome: 'Madrooba', qar: null, porque: 'Versão de café da casa do mingau salgado qatari.' },
    { nome: 'Machboos', qar: null, porque: 'Versão simples e barata do prato nacional, se você não for a um restaurante formal.' },
    { nome: 'Harees', qar: null, porque: 'Trigo e carne pilados. Comida de conforto do Golfo.' }
  ],
  porque: 'Parada de karak com comida qatari de verdade, em pleno Msheireb, por preço de café. Serve como plano B leve quando não se quer jantar formal.',
  tel: null,
  site: 'https://gahwetnaqatar.com/',
  reservaUrl: null,
  fontes: [{ t: 'Gahwetna — site oficial', u: 'https://gahwetnaqatar.com/' }, { t: 'Time Out Doha — restaurantes qataris', u: 'https://www.timeoutdoha.com/food-drink/qatari-restaurants-in-doha-to-try' }]
},
{
  id: 'sofra',
  nome: 'Sofra',
  status: 'aberto',
  statusNota: 'ATENÇÃO: não é turco nem fica dentro do Souq Waqif, ao contrário do que circula. É levantino, no térreo do Alwadi Hotel (Msheireb), a ~400 m do Souq.',
  cozinha: 'Levantina',
  categorias: ['arabe'],
  local: 'Alwadi Hotel Doha — MGallery, Msheireb',
  bairro: 'Msheireb',
  lat: 25.2884, lng: 51.5297,
  mapsQuery: 'Sofra Restaurant Alwadi Hotel Doha',
  distKm: 0.5, tempoMin: 3, aPe: true,
  precoQar: [100, 200],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Estimativa. Sem tabela pública verificada.',
  degustacao: null, brunch: null, almoco: { desc: 'Almoço e jantar', qar: null },
  alcool: null,
  alcoolNota: 'Não confirmado. Hotel MGallery — pode ter licença, mas não foi possível verificar.',
  reserva: 'recomendavel',
  ambiente: ['casual', 'hotel'],
  vista: null,
  rede: 'local',
  notas: { gastro: 7.0, autent: 7.0, custo: 7.5, doha: 5.5 },
  pratos: [
    { nome: 'Mezze levantino variado', qar: null, porque: 'É a proposta da casa: carta extensa de pratos do Levante.' }
  ],
  porque: 'Honestamente: não entra no seu roteiro. Com Argan a 1 minuto, Damasca One e Bandar Aden no Souq e SAWA a 5 minutos, não sobra motivo para gastar uma noite aqui. Fica na lista por ter sido pedido.',
  tel: null, site: null, reservaUrl: null,
  fontes: [{ t: 'Snoonu — Sofra Restaurant', u: 'https://snoonu.com/restaurants/sofra-restaurant' }]
},
{
  id: 'desert-rose',
  nome: 'Desert Rose Café',
  status: 'aberto',
  statusNota: 'MICHELIN Selected. Reaberto junto com os demais restaurantes do Qatar Museums em setembro/2026.',
  cozinha: 'Qatari moderna (chef Noof Al Marri)',
  categorias: ['qatari', 'cafe', 'local'],
  destaque: 'MICHELIN Selected · chef qatari',
  local: 'Museu Nacional do Catar — térreo, aberto para a lagoa e o pátio Baraha',
  bairro: 'NMoQ',
  lat: 25.2872, lng: 51.5510,
  mapsQuery: 'Desert Rose Cafe National Museum of Qatar Doha',
  distKm: 2.6, tempoMin: 8,
  precoQar: [60, 140],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Estimativa de café/almoço de museu. Sem tabela pública.',
  degustacao: null, brunch: null,
  almoco: { desc: 'Sáb–Qui 8h–18h · Sex 13h30–21h', qar: null },
  alcool: false,
  reserva: 'nao',
  ambiente: ['casual', 'design', 'luminoso'],
  vista: 'Lagoa do museu e pátio, sob a arquitetura de Jean Nouvel',
  rede: 'local',
  notas: { gastro: 8.0, autent: 9.0, custo: 8.5, doha: 8.5 },
  pratos: [
    { nome: 'Machboos com músculo de cordeiro', qar: null, porque: 'O MICHELIN cita nominalmente a versão da chef Noof — cordeiro cozido lentamente.' },
    { nome: 'Madrouba da chef Noof', qar: null, porque: 'Receita própria da chef, citada como diferencial da casa.' },
    { nome: 'Arroz com rubiyan (camarão)', qar: null, porque: 'Versão costeira, mais leve que o machboos de carne.' },
    { nome: 'Luqaimat', qar: null, porque: 'Bolinhas fritas com melaço de tâmara. A sobremesa nacional.' },
    { nome: 'Bolo de tâmara', qar: null, porque: 'Assinatura da casa com o café.' }
  ],
  porque: 'A forma barata e sem cerimônia de comer comida qatari feita por uma chef qatari reconhecida. Combina perfeitamente com a visita ao museu: almoce aqui, e reserve o Jiwan (mesmo prédio, 4º andar) para o jantar de outro dia.',
  tel: null,
  site: 'https://nmoq.org.qa/en/visit/desert-rose-cafe/',
  reservaUrl: null,
  fontes: [F.michelinQatari, F.qm, { t: 'NMoQ — Desert Rose Café (oficial)', u: 'https://nmoq.org.qa/en/visit/desert-rose-cafe/' }]
},
{
  id: 'smat',
  nome: 'SMAT',
  status: 'aberto',
  statusNota: 'MICHELIN Selected. Aberto 8h–00h.',
  cozinha: 'Qatari e do Golfo, alta gastronomia',
  categorias: ['qatari', 'alta', 'local'],
  destaque: 'MICHELIN Selected',
  local: 'Acima do Orient Pearl, extremo sul da Corniche',
  bairro: 'Corniche',
  lat: 25.2905, lng: 51.5390,
  mapsQuery: 'SMAT Restaurant Orient Pearl Corniche Doha',
  distKm: 1.8, tempoMin: 7,
  precoQar: [150, 300],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'MICHELIN marca a faixa como ﷼﷼﷼ (média-alta). Sem valores publicados.',
  degustacao: null, brunch: null, almoco: { desc: 'Aberto das 8h à meia-noite', qar: null },
  alcool: false,
  reserva: 'recomendavel',
  ambiente: ['sofisticado', 'família', 'salas privativas'],
  vista: 'Corniche e a orla',
  rede: 'local',
  notas: { gastro: 8.5, autent: 9.0, custo: 7.5, doha: 8.5 },
  pratos: [
    { nome: 'Mathawi macaroni', qar: null, porque: 'Macarrão à moda qatari — o tipo de prato de fusão local que não aparece em lista nenhuma de turista.' },
    { nome: 'Machboos', qar: null, porque: 'Versão refinada do prato nacional, em porção generosa.' },
    { nome: 'Luqaimat almas', qar: null, porque: 'Versão sofisticada da sobremesa nacional, assinatura da casa.' },
    { nome: 'Chickdemia', qar: null, porque: 'Criação da casa citada pela imprensa local. Curiosidade que só existe aqui.' }
  ],
  porque: 'A opção "qatari elegante sem ser museu": salas privativas, porções grandes, pensado para famílias qataris — o que significa que você vai estar cercado de locais, não de turistas. Boa alternativa ao Bayt Sharq se quiser algo mais moderno e menos histórico.',
  tel: null,
  site: 'https://orientpearlqatar.com/',
  reservaUrl: 'https://www.booknbook.qa/restaurant/smat-restaurant/profile',
  fontes: [{ t: 'MICHELIN — SMAT', u: 'https://guide.michelin.com/us/en/doha-region/doha_2433318/restaurant/smat' }, { t: 'Time Out Doha — restaurantes qataris', u: 'https://www.timeoutdoha.com/food-drink/qatari-restaurants-in-doha-to-try' }]
},

/* ============================================================
   3. WEST BAY / KATARA / PEARL — 12 a 25 min
   ============================================================ */
{
  id: 'jamavar',
  nome: 'Jamavar',
  status: 'aberto',
  statusNota: 'MANTEVE 1 estrela MICHELIN na edição Doha 2026.',
  cozinha: 'Indiana de alta gastronomia (norte e sul)',
  categorias: ['alta', 'internacional'],
  destaque: '★ MICHELIN',
  local: 'Sheraton Grand Doha Resort & Convention Hotel',
  bairro: 'West Bay',
  lat: 25.3208, lng: 51.5312,
  mapsQuery: 'Jamavar Doha Sheraton Grand',
  distKm: 7.5, tempoMin: 15,
  precoQar: [109, 450],
  precoNota: 'parcial',
  precoDetalhe: 'CONFIRMADO para almoço: business lunch de domingo a quinta, QAR 109 (2 tempos) e QAR 149 (3 tempos). Jantar e menu-degustação: preço NÃO confirmado.',
  degustacao: { nome: 'Menu-degustação assinatura', qar: null, confirmado: false },
  brunch: null,
  almoco: { desc: 'Business lunch Dom–Qui: 2 tempos QAR 109 · 3 tempos QAR 149', qar: 109 },
  alcool: true,
  alcoolNota: 'Sim — hotel Sheraton licenciado.',
  reserva: 'obrigatoria',
  ambiente: ['sofisticado', 'romântico', 'elegante'],
  vista: null,
  rede: 'internacional',
  redeNota: 'Grupo Leela/LSL (Londres, Dubai, Doha, Marrakech). A casa de Doha tem estrela própria.',
  notas: { gastro: 9.0, autent: 4.0, custo: 8.0, doha: 6.5 },
  pratos: [
    { nome: 'Menu-degustação assinatura', qar: null, porque: 'É o caminho para entender por que a casa tem estrela.' },
    { nome: 'Grelhados do tandoor', qar: null, porque: 'O guia destaca a seção de grelhados como um dos pontos fortes.' },
    { nome: 'Business lunch de 3 tempos (QAR 149)', qar: 149, porque: 'De longe o melhor custo-benefício de estrela MICHELIN em Doha: ~R$ 209 por pessoa. Se quiser uma estrela sem gastar, é aqui.' }
  ],
  porque: 'Cozinha excelente e o almoço é uma pechincha absurda para uma estrela. Mas seja honesto com a pergunta certa: indiano de alto nível você come em Londres, e provavelmente melhor. Como JANTAR numa viagem de 3 noites a Doha, perde para IDAM e Jiwan. Como ALMOÇO a QAR 149, é imbatível.',
  tel: null,
  site: 'https://jamavarrestaurants.com/doha/',
  reservaUrl: 'https://jamavarrestaurants.com/doha/',
  fontes: [F.michelin26, { t: 'Jamavar Doha — cardápios oficiais', u: 'https://jamavarrestaurants.com/doha/menus/' }, { t: 'Marriott — Jamavar', u: 'https://www.morecravings.com/en/venues/jamavar-doha' }]
},
{
  id: 'hakkasan',
  nome: 'Hakkasan',
  status: 'aberto',
  statusNota: 'Confirmado em operação. MICHELIN Selected. Nenhum indício de fechamento.',
  cozinha: 'Cantonesa contemporânea',
  categorias: ['alta', 'internacional'],
  local: 'The St. Regis Doha',
  bairro: 'West Bay Lagoon',
  lat: 25.3670, lng: 51.5290,
  mapsQuery: 'Hakkasan Doha St Regis',
  distKm: 13, tempoMin: 20,
  precoQar: [250, 500],
  precoNota: 'parcial',
  precoDetalhe: 'CONFIRMADOS: dim sum "Cantonese Treasure" QAR 98 (3 cestas) / QAR 148 (5 cestas); Botanical Brunch QAR 498; "Lost in Shanghai" QAR 128 (3 bebidas + 1 petisco). À la carte de jantar: NÃO confirmado.',
  degustacao: null,
  brunch: { desc: 'Botanical Brunch', qar: 498, confirmado: true },
  almoco: { desc: 'Dim sum de sábado: 3 cestas QAR 98 · 5 cestas QAR 148', qar: 98 },
  alcool: true,
  reserva: 'obrigatoria',
  ambiente: ['sofisticado', 'romântico', 'escuro', 'terraço'],
  vista: 'Terraço',
  rede: 'internacional',
  redeNota: 'Londres, Dubai, Abu Dhabi, Mumbai, Las Vegas, Miami… A marca mais replicada da sua lista.',
  notas: { gastro: 8.5, autent: 3.0, custo: 6.5, doha: 4.0 },
  pratos: [
    { nome: 'Costela wagyu defumada no chá jasmim', qar: null, porque: 'O prato de assinatura global da casa: 4 horas de braseado, defumado no wok sobre folhas de chá.' },
    { nome: 'Pato à Pequim', qar: null, porque: 'O clássico executado com rigor.' },
    { nome: 'Cantonese Treasure — 5 cestas (QAR 148)', qar: 148, porque: 'O único preço realmente bom da casa. Dim sum aos sábados.' }
  ],
  porque: 'É bom. Mas é Hakkasan: existe idêntico em Londres, Dubai e Las Vegas. Numa viagem de 3 noites a Doha, gastar uma delas aqui é desperdiçar a viagem. Se quiser experimentar, vá no dim sum de sábado ao meio-dia a QAR 148 — não no jantar.',
  tel: '+97444460170',
  site: 'https://hakkasangroup.com/venues/hakkasan-doha/',
  reservaUrl: 'https://hakkasangroup.com/venues/hakkasan-doha/',
  fontes: [{ t: 'Hakkasan — site oficial Doha', u: 'https://hakkasangroup.com/venues/hakkasan-doha/' }, { t: 'MICHELIN — Hakkasan', u: 'https://guide.michelin.com/us/en/doha-region/doha_2433318/restaurant/hakkasan-1197469' }, { t: 'Fact Qatar — dim sum de sábado', u: 'https://factqatar.com/hakkasan-doha-relaunches-its-saturday-dim-sum-lunch-experience/' }]
},
{
  id: 'nobu',
  nome: 'Nobu Doha',
  status: 'aberto',
  statusNota: 'Em operação; comemorou 10 anos em 2025. MICHELIN Selected.',
  cozinha: 'Japonesa-peruana (Nobu style)',
  categorias: ['alta', 'internacional'],
  destaque: 'O maior Nobu do mundo',
  local: 'Four Seasons Hotel Doha — pavilhão sobre a água',
  bairro: 'West Bay / Corniche Norte',
  lat: 25.3245, lng: 51.5285,
  mapsQuery: 'Nobu Doha Four Seasons',
  distKm: 8, tempoMin: 15,
  precoQar: [350, 700],
  precoNota: 'parcial',
  precoDetalhe: 'CONFIRMADOS: almoço-set QAR 165 (2 entradas + 1 principal; black cod tem acréscimo de QAR 50); brunch QAR 355 (sem álcool) / QAR 475 (com álcool); menus-degustação QAR 375 / 555 / 680 conforme a bebida. À la carte: não confirmado.',
  degustacao: { nome: 'Tasting menu (3 faixas conforme bebida)', qar: 375, confirmado: true, extra: 'QAR 375 com bebidas não alcoólicas · QAR 555 com álcool · QAR 680 com seleção premium' },
  brunch: { desc: 'Brunch', qar: 355, confirmado: true, extra: 'QAR 475 com álcool' },
  almoco: { desc: 'Set lunch', qar: 165, confirmado: true },
  alcool: true,
  reserva: 'obrigatoria',
  ambiente: ['sofisticado', 'romântico', 'espetacular', 'terraço'],
  vista: 'Pavilhão de dois andares sobre a água, com terraço e vista do Golfo',
  rede: 'internacional',
  redeNota: 'Dezenas de unidades no mundo. ESTA é a maior (2.415 m²) e o prédio é exclusivo.',
  notas: { gastro: 8.5, autent: 3.0, custo: 6.5, doha: 5.5 },
  pratos: [
    { nome: 'Black cod miso', qar: null, porque: 'O prato mais famoso da culinária de restaurante do século XX. Bacalhau-do-Alasca marinado em missô doce por dias. No set lunch sai por +QAR 50.' },
    { nome: 'Yellowtail jalapeño', qar: null, porque: 'O outro clássico Matsuhisa: olhete cru com jalapeño e molho de yuzu.' },
    { nome: 'Tiradito', qar: null, porque: 'A ponte peruana do Nobu — se você for a só UM peruano-japonês, é este prato que decide.' },
    { nome: 'Set lunch QAR 165', qar: 165, porque: 'A entrada mais barata na experiência: ~R$ 231 por pessoa.' }
  ],
  porque: 'Arquitetura espetacular e um dos Nobus mais bonitos que existem. Mas é Nobu — você pode comer o mesmo black cod em São Paulo, Londres ou Dubai. Vale se a vista e o prédio forem o ponto, e melhor ainda no almoço a QAR 165.',
  tel: null,
  site: 'https://noburestaurants.com/doha/',
  reservaUrl: 'https://noburestaurants.com/doha/',
  fontes: [{ t: 'Nobu Doha — cardápios oficiais', u: 'https://noburestaurants.com/doha/menus' }, { t: 'Four Seasons Doha — Nobu', u: 'https://www.fourseasons.com/doha/dining/menus/nobu-doha-dinner/' }, { t: 'Four Seasons — 10 anos do Nobu Doha', u: 'https://press.fourseasons.com/doha/hotel-news/2025/nobu-doha-10th-anniversary-events/' }, F.visitQatar]
},
{
  id: 'spice-market',
  nome: 'Spice Market',
  status: 'aberto',
  statusNota: 'Site oficial atualizado em 2026; em operação.',
  cozinha: 'Sudeste asiático (Jean-Georges Vongerichten)',
  categorias: ['internacional'],
  local: 'W Doha Hotel & Residences',
  bairro: 'West Bay',
  lat: 25.3195, lng: 51.5265,
  mapsQuery: 'Spice Market W Doha',
  distKm: 7.5, tempoMin: 14,
  precoQar: [200, 400],
  precoNota: 'parcial',
  precoDetalhe: 'Entradas a partir de QAR 30; brunch QAR 350–400 por pessoa. Jantar à la carte completo: não confirmado.',
  degustacao: null,
  brunch: { desc: 'Friday Brunch', qar: 350, confirmado: false, extra: 'faixa relatada QAR 350–400' },
  almoco: { desc: 'Almoço e jantar', qar: null },
  alcool: true,
  reserva: 'recomendavel',
  ambiente: ['animado', 'sofisticado', 'design'],
  vista: null,
  rede: 'internacional',
  notas: { gastro: 8.0, autent: 3.0, custo: 7.0, doha: 4.0 },
  pratos: [
    { nome: 'Costela de porco glaceada com gengibre (ou versão halal equivalente)', qar: null, porque: 'Assinatura Jean-Georges. Confirme a versão servida em Doha.' },
    { nome: 'Curry vermelho de camarão', qar: null, porque: 'O prato que fez a fama da casa em Nova York.' },
    { nome: 'Street food asiático de entrada (a partir de QAR 30)', qar: 30, porque: 'Melhor relação preço/prazer da carta.' }
  ],
  porque: 'Boa cozinha, mas é a definição de redundância no seu caso: você mora em São Paulo e tem sudeste asiático de alto nível. Corte da lista sem remorso.',
  tel: '+97444535135',
  site: 'https://www.spicemarketdoha.com/',
  reservaUrl: 'https://www.spicemarketdoha.com/',
  fontes: [{ t: 'Spice Market Doha — oficial', u: 'https://www.spicemarketdoha.com/' }, { t: 'Visit Qatar — Spice Market', u: 'https://visitqatar.com/intl-en/things-to-do/dining/restaurants/spice-market' }]
},
{
  id: 'coya',
  nome: 'COYA Doha',
  status: 'aberto',
  statusNota: 'Em operação no W Doha, West Bay — NÃO em Katara.',
  cozinha: 'Peruana contemporânea',
  categorias: ['internacional'],
  local: 'W Doha, West Bay',
  bairro: 'West Bay',
  lat: 25.3193, lng: 51.5267,
  mapsQuery: 'COYA Doha W Hotel West Bay',
  distKm: 7.5, tempoMin: 14,
  precoQar: [245, 400],
  precoNota: 'parcial',
  precoDetalhe: 'CONFIRMADOS: brunch "Vamos de Fiesta" (sextas, 12h–15h30) QAR 200 com bebidas leves / QAR 299 com bebidas premium; menus de compartilhar a partir de QAR 245; "Sol Y Sips" a partir de QAR 40 por item.',
  degustacao: { nome: 'Menu de compartilhar', qar: 245, confirmado: true },
  brunch: { desc: 'Vamos de Fiesta (sextas)', qar: 200, confirmado: true, extra: 'QAR 299 com bebidas premium' },
  almoco: { desc: 'Almoço diário 13h–16h', qar: null },
  alcool: true,
  reserva: 'recomendavel',
  ambiente: ['animado', 'festivo', 'música alta', 'DJ'],
  vista: null,
  rede: 'internacional',
  redeNota: 'Londres, Dubai, Mónaco, Abu Dhabi, Riade, Mykonos, Marbella…',
  notas: { gastro: 8.0, autent: 3.0, custo: 7.5, doha: 4.0 },
  pratos: [
    { nome: 'Arroz nikkei', qar: null, porque: 'Prato assinatura citado na abertura da casa.' },
    { nome: 'Costillas de res', qar: null, porque: 'Costela bovina em anticucho — o prato mais pedido do COYA no mundo.' },
    { nome: 'Ceviche clássico', qar: null, porque: 'A régua básica de qualquer peruano.' }
  ],
  porque: 'COYA é festa com boa comida; La Mar é comida séria com Gastón Acurio no nome. Se você só vai a um peruano, é La Mar. COYA entra se a noite for sobre ambiente e música, não sobre o prato.',
  tel: null,
  site: 'https://coyarestaurant.com/doha/en/food',
  reservaUrl: 'https://coyarestaurant.com/doha/en/food',
  fontes: [{ t: 'COYA Doha — oficial', u: 'https://coyarestaurant.com/doha/en/food' }, { t: 'Marhaba — COYA abre no W Doha', u: 'https://marhaba.qa/award-winning-peruvian-restaurant-coya-now-open-at-w-doha/' }, { t: 'MICHELIN — Coya', u: 'https://guide.michelin.com/en/doha-region/doha_2433318/restaurant/coya-1197425' }]
},
{
  id: 'la-mar',
  nome: 'La Mar by Gastón Acurio',
  status: 'aberto',
  statusNota: 'MICHELIN Selected 2026. ATENÇÃO: fica no InterContinental Doha Beach & Spa — NÃO no Mandarin Oriental.',
  cozinha: 'Peruana (Gastón Acurio)',
  categorias: ['alta', 'internacional', 'peixe'],
  destaque: 'MICHELIN Selected',
  local: 'InterContinental Doha Beach & Spa',
  bairro: 'West Bay Lagoon / Al Dafna',
  lat: 25.3610, lng: 51.5180,
  mapsQuery: 'La Mar by Gaston Acurio InterContinental Doha',
  distKm: 12, tempoMin: 20,
  precoQar: [300, 500],
  precoNota: 'parcial',
  precoDetalhe: 'CONFIRMADOS: "Sunset Hours" com cebiches, empanadas e makis a partir de QAR 39 e coquetéis a partir de QAR 35; brunch QAR 375 para duas pessoas ou QAR 645 para quatro. Jantar à la carte relatado em "QAR 500+ por pessoa" — número de agregador, NÃO confirmado por fonte oficial.',
  degustacao: null,
  brunch: { desc: 'Brunch de fim de semana', qar: 375, confirmado: true, extra: 'QAR 375 para 2 pessoas · QAR 645 para 4' },
  almoco: { desc: 'Sunset Hours: petiscos a partir de QAR 39', qar: 39 },
  alcool: true,
  reserva: 'obrigatoria',
  ambiente: ['romântico', 'sofisticado', 'praia', 'pôr do sol'],
  vista: 'Beira-mar, com o skyline de Doha em volta. A melhor vista de pôr do sol da lista.',
  rede: 'internacional',
  redeNota: 'Lima, San Francisco, Miami, Dubai… mas com curadoria direta do Acurio.',
  notas: { gastro: 9.0, autent: 3.5, custo: 7.0, doha: 6.0 },
  pratos: [
    { nome: 'Cebiche clássico', qar: null, porque: 'É a razão de existir da casa. Acurio é quem levou o cebiche ao mundo.' },
    { nome: 'Tiradito nikkei', qar: null, porque: 'O cruzamento peruano-japonês feito por quem inventou a categoria.' },
    { nome: 'Causa', qar: null, porque: 'Batata amarela prensada — prato peruano de casa, raro de ver bem feito fora do Peru.' },
    { nome: 'Sunset Hours (petiscos a partir de QAR 39)', qar: 39, porque: 'Cebiche a ~R$ 55 com vista de pôr do sol sobre o Golfo. O melhor programa barato de alta gastronomia em Doha.' }
  ],
  porque: 'Melhor peruano de Doha e uma das melhores vistas de pôr do sol. Se você quer um jantar romântico ocidental com vista, é a escolha mais forte depois do IDAM — e o "Sunset Hours" permite fazer isso barato.',
  tel: null,
  site: 'https://doha.intercontinental.com/la-mar-doha/',
  reservaUrl: 'https://doha.intercontinental.com/la-mar-doha/',
  fontes: [{ t: 'InterContinental Doha — La Mar (oficial)', u: 'https://doha.intercontinental.com/la-mar-doha/' }, { t: 'MICHELIN — La Mar', u: 'https://guide.michelin.com/us/en/doha-region/doha_2433318/restaurant/la-mar-by-gaston-acurio-1197554' }, { t: "World's 50 Best Discovery — La Mar", u: 'https://www.theworlds50best.com/discovery/Establishments/Qatar/Doha/La-Mar-Doha-by-Gast%C3%B3n-Acurio.html' }]
},
{
  id: 'mykonos',
  nome: 'Mykonos',
  status: 'aberto',
  statusNota: 'Em operação, aberto diariamente 12h–23h30.',
  cozinha: 'Grega',
  categorias: ['internacional', 'peixe'],
  local: 'InterContinental Doha Beach & Spa',
  bairro: 'West Bay Lagoon',
  lat: 25.3612, lng: 51.5182,
  mapsQuery: 'Mykonos Restaurant InterContinental Doha',
  distKm: 12, tempoMin: 20,
  precoQar: [180, 350],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Só foi possível confirmar coquetéis a partir de QAR 50. Faixa de comida é estimativa.',
  degustacao: null, brunch: null, almoco: { desc: 'Aberto o dia todo', qar: null },
  alcool: true,
  reserva: 'recomendavel',
  ambiente: ['casual-sofisticado', 'praia', 'família'],
  vista: 'Praia do InterContinental',
  rede: 'local',
  notas: { gastro: 7.0, autent: 3.0, custo: 6.5, doha: 3.5 },
  pratos: [
    { nome: 'Peixe inteiro grelhado', qar: null, porque: 'É o que se pede num grego à beira-mar.' },
    { nome: 'Mezze grego', qar: null, porque: 'Tzatziki, taramosalata, saganaki.' }
  ],
  porque: 'Grego correto de hotel, sem nada que justifique a viagem. Entre Gaia e Mykonos, Gaia ganha em cozinha e em ambiente. Corte.',
  tel: null,
  site: 'https://doha.intercontinental.com/mykonos-doha/',
  reservaUrl: 'https://doha.intercontinental.com/mykonos-doha/',
  fontes: [{ t: 'InterContinental Doha — Mykonos (oficial)', u: 'https://doha.intercontinental.com/mykonos-doha/' }]
},
{
  id: 'gaia',
  nome: 'GAIA Doha',
  status: 'aberto',
  statusNota: 'Em operação. Sáb–Qua 12h–15h30 e 19h–22h30 · Qui–Sex até 23h.',
  cozinha: 'Grega-mediterrânea (chef Izu Ani)',
  categorias: ['internacional', 'peixe', 'romantico'],
  local: 'Orla de West Bay',
  bairro: 'West Bay',
  lat: 25.3230, lng: 51.5300,
  mapsQuery: 'GAIA Doha restaurant West Bay',
  distKm: 8, tempoMin: 15,
  precoQar: [250, 450],
  precoNota: 'parcial',
  precoDetalhe: 'Só foi possível confirmar sobremesas em QAR 55–135. O restante da faixa é estimativa.',
  degustacao: null, brunch: null, almoco: { desc: 'Almoço 12h–15h30', qar: null },
  alcool: true,
  reserva: 'obrigatoria',
  ambiente: ['sofisticado', 'romântico', 'animado', 'orla'],
  vista: 'Beira-d\'água em West Bay',
  rede: 'internacional',
  redeNota: 'Dubai, Mónaco, Londres, Marbella, e Miami em 2026.',
  notas: { gastro: 8.5, autent: 3.0, custo: 6.0, doha: 4.5 },
  pratos: [
    { nome: 'Peixe do dia no balcão (salgado em crosta, harissa, grelhado ou na frigideira)', qar: null, porque: 'O formato-assinatura da casa: você escolhe a peça e o preparo.' },
    { nome: 'Mezze grego do Izu Ani', qar: null, porque: 'O que fez a fama da marca em Dubai.' }
  ],
  porque: 'É o melhor grego-mediterrâneo de Doha e muito superior ao Mykonos. Mas continua sendo uma marca de Dubai que você pode comer em quatro outras cidades. Só entra num roteiro de 4 noites.',
  tel: null,
  site: 'https://gaia-restaurants.com/doha-restaurant/gaia-doha',
  reservaUrl: 'https://gaia-restaurants.com/doha-restaurant/gaia-doha',
  fontes: [{ t: 'GAIA Doha — cardápios oficiais', u: 'https://gaia-restaurants.com/doha-restaurant/gaia-doha-menus' }, { t: 'Time Out Doha — melhores gregos', u: 'https://www.timeoutdoha.com/food-drink/greek-restaurants-doha-qatar' }]
},
{
  id: 'saffron-lounge',
  nome: 'Saffron Lounge',
  status: 'aberto',
  statusNota: 'AMBIGUIDADE NA SUA LISTA: existem dois "Saffron" em Doha. (1) Saffron Lounge — indiano do chef Vineet Bhatia, em Katara. (2) Saffron — tailandês do Banyan Tree Doha. Este registro é o de Katara, que é o mais relevante.',
  cozinha: 'Indiana (chef Vineet Bhatia)',
  categorias: ['internacional'],
  local: 'Edifício 26, Katara Cultural Village',
  bairro: 'Katara',
  lat: 25.3585, lng: 51.5258,
  mapsQuery: 'Saffron Lounge Katara Cultural Village Doha',
  distKm: 12.5, tempoMin: 20,
  precoQar: [180, 350],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Sem tabela pública verificada.',
  degustacao: null, brunch: null, almoco: { desc: 'Almoço e jantar', qar: null },
  alcool: null,
  alcoolNota: 'Não confirmado. Katara tem venues com e sem licença.',
  reserva: 'recomendavel',
  ambiente: ['sofisticado', 'terraço'],
  vista: 'Terraço sobre Katara, perto do mar',
  rede: 'local',
  notas: { gastro: 8.0, autent: 3.5, custo: 6.5, doha: 4.5 },
  pratos: [
    { nome: 'Butter chicken', qar: null, porque: 'O clássico, na mão de um chef que teve estrela MICHELIN em Londres.' },
    { nome: 'Tandoori', qar: null, porque: 'A seção forte da carta.' }
  ],
  porque: 'Se você quer indiano em Doha, Jamavar tem estrela MICHELIN e almoço a QAR 149. Saffron Lounge é redundante. Fica na lista só porque você pediu — e com o alerta de que talvez você estivesse pensando no tailandês do Banyan Tree.',
  tel: null,
  site: 'https://www.katara.net/en/Visiting/Venues-Landmarks/Saffron-Lounge',
  reservaUrl: null,
  fontes: [{ t: 'Katara — Saffron Lounge (oficial)', u: 'https://www.katara.net/en/Visiting/Venues-Landmarks/Saffron-Lounge' }, { t: 'Banyan Tree Doha — Saffron (tailandês)', u: 'https://www.banyantree.com/qatar/doha/dining/saffron' }]
},
{
  id: 'bibo',
  nome: 'BiBo Doha — Dani García',
  status: 'aberto',
  statusNota: 'CONFLITO DE FONTES sobre a localização: a página oficial do Kempinski coloca o BiBo no Marsa Malaz Kempinski, The Pearl; outras fontes citam o St. Regis. Considero a página do hotel (Kempinski) a mais confiável. CONFIRME o endereço ao reservar.',
  cozinha: 'Andaluza contemporânea',
  categorias: ['alta', 'internacional'],
  local: 'Marsa Malaz Kempinski, The Pearl (verificar)',
  bairro: 'The Pearl',
  lat: 25.3710, lng: 51.5470,
  mapsQuery: 'BiBo Dani Garcia Doha',
  distKm: 17, tempoMin: 23,
  precoQar: [300, 550],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Não foi possível confirmar nenhum preço atual.',
  degustacao: null, brunch: null, almoco: { desc: 'Não confirmado', qar: null },
  alcool: true,
  reserva: 'obrigatoria',
  ambiente: ['animado', 'colorido', 'teatral'],
  vista: 'The Pearl',
  rede: 'internacional',
  redeNota: 'Marbella, Madri, Londres (Shoreditch), Tarifa, Doha.',
  notas: { gastro: 8.5, autent: 3.0, custo: 6.0, doha: 4.0 },
  pratos: [
    { nome: 'Brioche de rabo de toro', qar: null, porque: 'O prato-assinatura do Dani García no mundo inteiro.' },
    { nome: 'Croquetas de lula', qar: null, porque: 'Citadas repetidamente como o melhor petisco da casa.' },
    { nome: 'Paella de ribeye', qar: null, porque: 'A releitura andaluza mais comentada da carta de Doha.' }
  ],
  porque: 'Divertido e bem feito, mas é espanhol de marca internacional a 23 minutos do seu hotel, com preço não confirmado e até o endereço em disputa entre fontes. Corte.',
  tel: null,
  site: 'https://grupodanigarcia.com/en/doha/',
  reservaUrl: 'https://grupodanigarcia.com/en/booking/bibo-doha/',
  fontes: [{ t: 'Grupo Dani García — Doha (oficial)', u: 'https://grupodanigarcia.com/en/doha/' }, { t: 'Marsa Malaz Kempinski — BiBo (oficial)', u: 'https://www.kempinski.com/en/marsa-malaz-kempinski-the-pearl-doha/restaurants-bars/bibo' }, { t: 'MICHELIN — BiBo', u: 'https://guide.michelin.com/gb/en/doha-region/doha_2433318/restaurant/bibo-1197711' }]
},
{
  id: 'saffron-banyan',
  nome: 'Saffron (Banyan Tree)',
  status: 'inconclusivo',
  statusNota: 'Tailandês do Banyan Tree Doha. Não foi possível confirmar operação atual em setembro/2026 por fonte primária.',
  cozinha: 'Tailandesa',
  categorias: ['internacional'],
  local: 'Banyan Tree Doha, Mushereib',
  bairro: 'Msheireb',
  lat: 25.2890, lng: 51.5240,
  mapsQuery: 'Saffron Banyan Tree Doha Thai restaurant',
  distKm: 1.5, tempoMin: 6,
  precoQar: [180, 320],
  precoNota: 'nao-confirmado',
  degustacao: null, brunch: null, almoco: null,
  alcool: null,
  reserva: 'recomendavel',
  ambiente: ['sofisticado', 'hotel'],
  vista: null,
  rede: 'internacional',
  notas: { gastro: null, autent: 3.0, custo: null, doha: 3.0 },
  pratos: [],
  porque: 'Registro aberto para desambiguar o "Saffron" da sua lista. Se for este que você tinha em mente, o Isaan (Bib Gourmand) é a melhor casa tailandesa de Doha hoje.',
  tel: null,
  site: 'https://www.banyantree.com/qatar/doha/dining/saffron',
  reservaUrl: null,
  fontes: [{ t: 'Banyan Tree Doha — Saffron (oficial)', u: 'https://www.banyantree.com/qatar/doha/dining/saffron' }]
},

/* ============================================================
   4. AL MAHA ISLAND / LUSAIL — 22 a 30 min
   ============================================================ */
{
  id: 'zuma',
  nome: 'Zuma Doha',
  status: 'aberto',
  statusNota: 'Em operação em Al Maha Island (NÃO no Gate Mall). MICHELIN Selected.',
  cozinha: 'Japonesa contemporânea / izakaya',
  categorias: ['alta', 'internacional'],
  local: 'Al Maha Island, Lusail',
  bairro: 'Al Maha Island',
  lat: 25.3790, lng: 51.5330,
  mapsQuery: 'Zuma Doha Al Maha Island',
  distKm: 22, tempoMin: 27,
  precoQar: [350, 600],
  precoNota: 'parcial',
  precoDetalhe: 'CONFIRMADOS: almoço especial Dom–Qui 13h–15h30 a QAR 139; brunch "Baikingu" QAR 425 (bebidas leves) / QAR 550 (seleção do sommelier) / QAR 650 (espumante italiano + sommelier); sobremesa de robata QAR 65. À la carte de jantar: não confirmado.',
  degustacao: null,
  brunch: { desc: 'Baikingu Brunch', qar: 425, confirmado: true, extra: 'QAR 550 e QAR 650 nas faixas com bebidas' },
  almoco: { desc: 'Lunch special Dom–Qui', qar: 139, confirmado: true },
  alcool: true,
  reserva: 'obrigatoria',
  reservaNota: 'SevenRooms. Dress code smart elegant — sem bermuda, chinelo ou roupa esportiva. Mesa de 2–6 pessoas: 2 horas.',
  ambiente: ['animado', 'sofisticado', 'DJ', 'terraço'],
  vista: 'Terraço voltado para o mar',
  rede: 'internacional',
  redeNota: 'Londres, Dubai, Miami, Roma, Nova York, Bangkok…',
  notas: { gastro: 9.0, autent: 3.0, custo: 6.0, doha: 4.5 },
  pratos: [
    { nome: 'Black cod em folha de hoba', qar: null, porque: 'O prato-assinatura do Zuma no mundo. Se for uma vez só, é este.' },
    { nome: 'Filé bovino picante no robata', qar: null, porque: 'O outro clássico da casa, citado nominalmente pela marca.' },
    { nome: 'Costeletas de cordeiro no robata', qar: null, porque: 'A grelha é o ponto forte do Zuma, não o sushi.' },
    { nome: 'Almoço especial QAR 139', qar: 139, porque: 'De longe a melhor forma de conhecer a casa: ~R$ 195 por pessoa.' }
  ],
  porque: 'Zuma é provavelmente o melhor japonês contemporâneo de Doha. Mas são 27 minutos de carro do Souq, é a mesma casa de Londres e Dubai, e o jantar é caro. Se quiser conhecer, faça o almoço a QAR 139.',
  tel: '+97444971666',
  site: 'https://www.zumarestaurant.com/en/doha',
  reservaUrl: 'https://www.sevenrooms.com/reservations/zumadoha',
  fontes: [{ t: 'Zuma Doha — cardápio oficial', u: 'https://www.zumarestaurant.com/en/doha/menu' }, { t: 'Zuma Doha — reservas (SevenRooms)', u: 'https://www.sevenrooms.com/reservations/zumadoha' }, { t: 'MICHELIN — Zuma', u: 'https://guide.michelin.com/qa/en/doha-region/doha_2433318/restaurant/zuma-1213875' }, { t: 'iamQatar — Baikingu Brunch', u: 'https://iamqatar.qa/pages/feed-post/zuma-doha-announces-the-return-of-its-popular-baikingu-brunch/' }]
},
{
  id: 'lpm',
  nome: 'LPM Restaurant & Bar (La Petite Maison)',
  status: 'aberto',
  statusNota: 'CONFIRMADO: voltou a servir ALMOÇO a partir de 1º DE SETEMBRO DE 2026, depois de fechar as tardes no verão. MICHELIN Selected.',
  cozinha: 'Francesa-mediterrânea (Nice)',
  categorias: ['alta', 'internacional'],
  destaque: 'Almoço reaberto em 01/09/2026',
  local: 'Al Maha Island, Lusail',
  bairro: 'Al Maha Island',
  lat: 25.3785, lng: 51.5338,
  mapsQuery: 'LPM Restaurant Bar Doha Al Maha Island',
  distKm: 22, tempoMin: 27,
  precoQar: [150, 450],
  precoNota: 'parcial',
  precoDetalhe: 'CONFIRMADOS (almoço, Dom–Qui 12h30–15h): "Le Petit Menu" QAR 150 (entrada + principal) e "Le Grand Menu" QAR 190 (entrada + principal + sobremesa). Brunch "La Vie en Rosé" aos sábados: preço não confirmado. Jantar à la carte: não confirmado.',
  degustacao: null,
  brunch: { desc: 'La Vie en Rosé (sábados)', qar: null, confirmado: false },
  almoco: { desc: 'Business lunch Dom–Qui: QAR 150 (2 tempos) · QAR 190 (3 tempos)', qar: 150, confirmado: true },
  alcool: true,
  reserva: 'obrigatoria',
  ambiente: ['sofisticado', 'romântico', 'luminoso', 'terraço', 'arte'],
  vista: 'Terraço na ilha, salão com arte colorida',
  rede: 'internacional',
  redeNota: 'Londres, Dubai, Abu Dhabi, Miami, Riade, Hong Kong, Mykonos…',
  notas: { gastro: 8.5, autent: 3.0, custo: 8.0, doha: 4.5 },
  pratos: [
    { nome: 'Crevettes tièdes à l\'huile d\'olive', qar: null, porque: 'O prato-assinatura mundial do LPM: camarões mornos no azeite. Simples e perfeito.' },
    { nome: 'Confit de canard com laranja e endívia', qar: null, porque: 'O clássico francês da casa.' },
    { nome: 'Dourada inteira assada com ervas', qar: null, porque: 'Para dividir a dois.' },
    { nome: 'Le Grand Menu (QAR 190)', qar: 190, porque: '3 tempos de cozinha francesa de nível por ~R$ 266. Um dos melhores negócios gastronômicos de Doha.' }
  ],
  porque: 'Excelente, mas é Nice servido na mesma toalha em dez cidades. Vale como ALMOÇO a QAR 190 se você já estiver em Lusail — nunca como uma das suas três noites.',
  tel: null,
  site: 'https://lpmrestaurants.com/doha/',
  reservaUrl: 'https://lpmrestaurants.com/doha/',
  fontes: [{ t: 'LPM Doha — business lunch (oficial)', u: 'https://lpmrestaurants.com/doha/menus/businesslunch/' }, { t: 'LPM Doha — brunch (oficial)', u: 'https://lpmrestaurants.com/doha/menus/brunch/' }, { t: 'Marhaba — Business Lunch no LPM', u: 'https://marhaba.qa/business-lunch-at-lpm-restaurant-bar-doha/' }, { t: 'MICHELIN — LPM', u: 'https://guide.michelin.com/en/doha-region/doha_2433318/restaurant/la-petite-maison-lpm' }]
},
{
  id: 'em-sherif',
  nome: 'Em Sherif Restaurant Qatar',
  status: 'aberto',
  statusNota: 'MICHELIN Selected 2026. Em Al Maha Island. ATENÇÃO: existem TRÊS marcas Em Sherif em Doha — o Restaurant (Al Maha Island), o Café (Millennium Hotel) e uma unidade no Sheraton. Confirme qual você está reservando.',
  cozinha: 'Libanesa de alta gastronomia',
  categorias: ['arabe', 'alta'],
  destaque: 'MICHELIN Selected',
  local: 'Al Maha Island, Lusail',
  bairro: 'Al Maha Island',
  lat: 25.3788, lng: 51.5342,
  mapsQuery: 'Em Sherif Restaurant Qatar Al Maha Island Doha',
  distKm: 22, tempoMin: 27,
  precoQar: [250, 450],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'A casa opera com MENU FIXO compartilhado, não à la carte. O MICHELIN marca a faixa de preço máxima (﷼﷼﷼﷼). O único número que apareceu foi um menu de iftar a QAR 220 de um Ramadã anterior — NÃO usar como referência. Peça o preço do set menu ao reservar.',
  degustacao: { nome: 'Set menu compartilhado (formato único da casa)', qar: null, confirmado: false },
  brunch: null, almoco: { desc: 'Almoço e jantar', qar: null },
  alcool: true,
  reserva: 'obrigatoria',
  ambiente: ['sofisticado', 'romântico', 'opulento'],
  vista: 'Al Maha Island',
  rede: 'internacional',
  redeNota: 'Beirute, Londres, Mónaco, Dubai, Riade, Doha, Cannes.',
  notas: { gastro: 8.5, autent: 6.0, custo: 5.5, doha: 5.5 },
  pratos: [
    { nome: 'Mezze completo (vem por padrão no set menu)', qar: null, porque: 'É o motivo de existir da casa: dezenas de pratinhos libaneses em sequência.' },
    { nome: 'Kibbeh nayyeh', qar: null, porque: 'O kibe cru libanês bem feito — a régua de qualquer casa séria.' },
    { nome: 'Grelhados de cordeiro', qar: null, porque: 'A parte quente do menu fixo.' }
  ],
  porque: 'Libanês de altíssimo nível, mas com três problemas para você: preço alto e não confirmado, 27 minutos de carro, e libanês de qualidade é a cozinha árabe que o Brasil tem MELHOR representada. Você não precisa cruzar o mundo para comer bem libanês. Prefira o qatari, o iemenita e o marroquino.',
  tel: null,
  site: 'https://emsherif.com/',
  reservaUrl: 'https://emsherif.com/',
  fontes: [{ t: 'MICHELIN — Em Sherif', u: 'https://guide.michelin.com/qa/en/doha-region/doha_2433318/restaurant/em-sherif-1217716' }, { t: 'Em Sherif — site oficial', u: 'https://emsherif.com/' }]
},
{
  id: 'alba',
  nome: 'Alba',
  status: 'aberto',
  statusNota: 'NOVA ESTRELA MICHELIN na edição Doha 2026 — promovida este ano. Chef Cristhian Serraino.',
  cozinha: 'Italiana do norte (Piemonte)',
  categorias: ['alta', 'internacional'],
  destaque: '★ MICHELIN · nova estrela 2026',
  local: 'Raffles Doha, 1º andar — Katara Towers, Lusail',
  bairro: 'Lusail',
  lat: 25.3690, lng: 51.5290,
  mapsQuery: 'Alba Raffles Doha Katara Towers Lusail',
  distKm: 20, tempoMin: 25,
  precoQar: [450, 800],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Há dois "Menù Degustazione" — 4 tempos e 6 tempos — mas nenhum preço foi publicado. Pergunte ao reservar.',
  degustacao: { nome: 'Menù Degustazione (4 ou 6 tempos)', qar: null, confirmado: false },
  brunch: null, almoco: { desc: 'Não confirmado', qar: null },
  alcool: true,
  reserva: 'obrigatoria',
  ambiente: ['sofisticado', 'romântico', 'luxo'],
  vista: 'Dentro das Katara Towers (as "cimitarras" de Lusail)',
  rede: 'local',
  redeNota: 'Casa única, dentro do Raffles Doha. Não é filial de nada.',
  notas: { gastro: 9.5, autent: 3.0, custo: 5.0, doha: 6.0 },
  pratos: [
    { nome: 'Bochecha de vitela braseada no Barolo', qar: null, porque: 'O prato que o MICHELIN cita nominalmente ao justificar a estrela.' },
    { nome: 'Spaghetti com ragù de camarão', qar: null, porque: 'O outro prato destacado pelo guia.' },
    { nome: 'Atum Balfegó', qar: null, porque: 'Atum de criação espanhola de altíssimo padrão — a casa é citada por trabalhá-lo.' }
  ],
  porque: 'É a novidade gastronômica de 2026 em Doha e a única estrela nova do ano. Cozinha piemontesa levada muito a sério. Mas é italiano — e você tem italiano excelente no Brasil. Entra num roteiro de 4 noites, ou se estrela MICHELIN nova for o critério.',
  tel: '+97440307100',
  site: 'https://www.raffles.com/doha/',
  reservaUrl: 'https://restaurantsandbars.accor.com/en/restaurant/B662_R002',
  fontes: [F.michelin26, { t: 'MICHELIN — Alba', u: 'https://guide.michelin.com/qa/en/doha-region/doha_2433318/restaurant/alba-1213877' }, { t: 'Raffles Doha — Alba (oficial)', u: 'https://restaurantsandbars.accor.com/en/restaurant/B662_R002' }, { t: 'Marhaba — Alba reabre com experiência de estrela', u: 'https://marhaba.qa/alba-reopens-at-raffles-doha-with-michelin%E2%80%91star-culinary-experience/' }]
},
{
  id: 'berenjak',
  nome: 'Berenjak Al Maha',
  status: 'aberto',
  statusNota: 'NOVO Bib Gourmand na edição MICHELIN Doha 2026.',
  cozinha: 'Persa (kebabs na brasa)',
  categorias: ['arabe', 'alta-acessivel'],
  destaque: 'BIB GOURMAND · novo em 2026',
  local: 'Al Maha Island, Lusail',
  bairro: 'Al Maha Island',
  lat: 25.3792, lng: 51.5336,
  mapsQuery: 'Berenjak Al Maha Island Doha',
  distKm: 22, tempoMin: 27,
  precoQar: [130, 250],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Estimativa a partir do posicionamento Bib Gourmand.',
  degustacao: null, brunch: null, almoco: { desc: 'Almoço e jantar', qar: null },
  alcool: null,
  reserva: 'recomendavel',
  ambiente: ['casual-sofisticado', 'animado', 'brasa aberta'],
  vista: 'Al Maha Island',
  rede: 'internacional',
  redeNota: 'Grupo JKS (Londres). Unidade de Doha é a do Golfo.',
  notas: { gastro: 8.5, autent: 6.0, custo: 8.5, doha: 6.0 },
  pratos: [
    { nome: 'Kebabs na brasa de carvão', qar: null, porque: 'É o que o MICHELIN cita ao dar o Bib: kebabs cozidos sobre brasa.' },
    { nome: 'Khoresh (ensopados persas)', qar: null, porque: 'A parte da carta que quase ninguém pede e que é a alma da cozinha persa.' },
    { nome: 'Pães frescos', qar: null, porque: 'Feitos na casa, citados nominalmente pelo guia.' }
  ],
  porque: 'Se você quer persa, a pergunta é: Parisa (a pé do hotel, salão espetacular, comida boa) ou Berenjak (27 min de carro, Bib Gourmand, comida melhor)? Para uma viagem curta, Parisa ganha pela logística.',
  tel: null,
  site: 'https://berenjak.com/locations/al-maha-island/',
  reservaUrl: 'https://berenjak.com/locations/al-maha-island/',
  fontes: [F.michelin26, { t: 'Berenjak — Al Maha Island (oficial)', u: 'https://berenjak.com/locations/al-maha-island/' }]
},
{
  id: 'morimoto',
  nome: 'Morimoto Doha',
  status: 'aberto',
  statusNota: 'Em operação, diariamente 18h–23h.',
  cozinha: 'Japonesa (chef Masaharu Morimoto)',
  categorias: ['alta', 'internacional'],
  local: 'Mondrian Doha',
  bairro: 'West Bay Lagoon',
  lat: 25.3640, lng: 51.5250,
  mapsQuery: 'Morimoto Mondrian Doha',
  distKm: 14, tempoMin: 20,
  precoQar: [300, 600],
  precoNota: 'parcial',
  precoDetalhe: 'Faixas relatadas: entradas QAR 80–150; principais de robata QAR 180–380; wagyu a preço de mercado. Terças "Rolls & Ramen" QAR 210; brunch de sexta a partir de QAR 350. As faixas de carta vêm de veículos secundários — trate como indicativas.',
  degustacao: { nome: 'Omakase', qar: null, confirmado: false },
  brunch: { desc: 'Brunch de sexta (buffet aberto de maki, sushi e sashimi)', qar: 350, confirmado: false },
  almoco: { desc: 'Só jantar (18h–23h)', qar: null },
  alcool: true,
  reserva: 'obrigatoria',
  ambiente: ['sofisticado', 'escuro', 'balcão de sushi'],
  vista: null,
  rede: 'internacional',
  redeNota: 'Primeiro Morimoto do Oriente Médio, mas a marca existe em Nova York, Napa, Las Vegas, Tóquio, Maui…',
  notas: { gastro: 8.5, autent: 3.0, custo: 6.0, doha: 4.0 },
  pratos: [
    { nome: 'Omakase no balcão (16 lugares)', qar: null, porque: 'Se for a este endereço, é no balcão. O salão não justifica o preço.' },
    { nome: 'Robata', qar: null, porque: 'A seção onde a casa é mais consistente.' }
  ],
  porque: 'Terceiro japonês da sua lista. Zuma, Nobu e Morimoto competem pela mesma noite e você não deve reservar mais de um. Entre os três, Morimoto é o que menos se distingue em Doha. Corte.',
  tel: '+97440455555',
  site: 'https://mondrianhotels.com/doha/dining/morimoto/',
  reservaUrl: 'https://mondrianhotels.com/doha/dining/morimoto/',
  fontes: [{ t: 'Mondrian Doha — Morimoto (oficial)', u: 'https://mondrianhotels.com/doha/dining/morimoto/' }, { t: 'Mondrian Doha — cardápio', u: 'https://mondrianhotels.com/doha/dining/morimoto/menu/' }]
},
{
  id: 'fenyal',
  nome: 'Fenyal',
  status: 'aberto',
  statusNota: 'NOVO Bib Gourmand MICHELIN 2026. Aberto todos os dias, 7h–23h.',
  cozinha: 'Qatari contemporânea',
  categorias: ['qatari', 'local', 'cafe'],
  destaque: 'BIB GOURMAND · novo em 2026',
  local: 'Crystal Walk, Gewan Island',
  bairro: 'Gewan Island',
  lat: 25.3830, lng: 51.5540,
  mapsQuery: 'Fenyal Gewan Island Doha',
  distKm: 20, tempoMin: 25,
  precoQar: [80, 180],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Estimativa a partir do posicionamento Bib Gourmand.',
  degustacao: null,
  brunch: { desc: 'Café da manhã com balaleet e foul', qar: null },
  almoco: { desc: 'Aberto 7h–23h', qar: null },
  alcool: false,
  reserva: 'recomendavel',
  ambiente: ['casual-sofisticado', 'majlis', 'moderno'],
  vista: 'Crystal Walk, Gewan Island',
  rede: 'local',
  notas: { gastro: 8.5, autent: 9.0, custo: 9.0, doha: 8.5 },
  pratos: [
    { nome: 'Balaleet', qar: null, porque: 'Citado pelo MICHELIN como destaque do café da manhã da casa.' },
    { nome: 'Chicken nashif', qar: null, porque: 'Prato qatari de frango desfiado com tomate. Raro em carta de restaurante.' },
    { nome: 'Kofta de cordeiro e costelas com homus', qar: null, porque: 'A seção quente destacada pelo guia.' },
    { nome: 'Café árabe na dallah', qar: null, porque: 'Servido no bule tradicional — o ritual completo.' }
  ],
  porque: 'A melhor novidade qatari de 2026 segundo o MICHELIN. O problema é puramente logístico: 25 minutos de carro numa ilha nova. Se você tivesse 5 noites, seria parada obrigatória; em 3, perde para Jiwan e Bayt Sharq por distância.',
  tel: null, site: null, reservaUrl: null,
  fontes: [F.michelin26, F.michelinLocal, { t: 'MICHELIN — Fenyal', u: 'https://guide.michelin.com/us/en/doha-region/doha_2433318/restaurant/fenyal' }]
},
{
  id: 'mila',
  nome: 'Mila',
  status: 'aberto',
  statusNota: 'NOVO Bib Gourmand MICHELIN 2026.',
  cozinha: 'Mediterrânea e levantina, pratos para dividir',
  categorias: ['arabe', 'internacional', 'alta-acessivel'],
  destaque: 'BIB GOURMAND · novo em 2026',
  local: 'Rosewood Doha, 1º andar',
  bairro: 'Lusail / Marina District',
  lat: 25.3745, lng: 51.5255,
  mapsQuery: 'Mila Rosewood Doha restaurant',
  distKm: 19, tempoMin: 24,
  precoQar: [150, 280],
  precoNota: 'nao-confirmado',
  degustacao: null, brunch: null, almoco: { desc: 'Não confirmado', qar: null },
  alcool: true,
  reserva: 'recomendavel',
  ambiente: ['sofisticado', 'moderno'],
  vista: 'Rosewood Doha',
  rede: 'local',
  notas: { gastro: 8.5, autent: 5.5, custo: 8.5, doha: 6.0 },
  pratos: [
    { nome: 'Pratos mediterrâneo-levantinos para dividir', qar: null, porque: 'É o formato da casa segundo o MICHELIN.' }
  ],
  porque: 'Bom, novo e bem avaliado, mas é mais um mediterrâneo — categoria em que sua lista já tem LPM, Gaia e Mykonos brigando. Fica como alternativa se você acabar hospedado em Lusail.',
  tel: null, site: null, reservaUrl: null,
  fontes: [F.michelin26, { t: 'Discover Qatar — MICHELIN Doha 2026', u: 'https://www.discoverqatar.qa/travel-journal/michelin-guide-doha-2026/' }]
},
{
  id: 'isaan',
  nome: 'Isaan',
  status: 'aberto',
  statusNota: 'Manteve o Bib Gourmand MICHELIN em 2026.',
  cozinha: 'Tailandesa',
  categorias: ['internacional', 'alta-acessivel'],
  destaque: 'BIB GOURMAND',
  local: 'Doha (verificar endereço ao reservar)',
  bairro: 'Doha',
  lat: 25.3200, lng: 51.5300,
  mapsQuery: 'Isaan Thai restaurant Doha Michelin',
  distKm: 8, tempoMin: 15,
  precoQar: [130, 250],
  precoNota: 'nao-confirmado',
  degustacao: null, brunch: null, almoco: { desc: 'Não confirmado', qar: null },
  alcool: null,
  reserva: 'recomendavel',
  ambiente: ['casual-sofisticado', 'cozinha aberta'],
  vista: 'Vista para a cozinha aberta',
  rede: 'local',
  notas: { gastro: 8.5, autent: 4.0, custo: 8.5, doha: 5.0 },
  pratos: [
    { nome: 'Dumplings de frango no vapor', qar: null, porque: 'Destaque citado pelo MICHELIN.' },
    { nome: 'Pad thai de lagosta', qar: null, porque: 'O prato mais comentado da casa.' },
    { nome: 'Mango sticky rice', qar: null, porque: 'A sobremesa que o guia menciona.' }
  ],
  porque: 'Se o "Saffron" da sua lista era o tailandês do Banyan Tree, esta é a casa certa: o tailandês que o MICHELIN premiou em Doha. Ainda assim, tailandês não é razão para vir ao Catar.',
  tel: null, site: null, reservaUrl: null,
  fontes: [F.michelin26, { t: 'Discover Qatar — MICHELIN Doha 2026', u: 'https://www.discoverqatar.qa/travel-journal/michelin-guide-doha-2026/' }]
},
{
  id: 'baron',
  nome: 'Baron',
  status: 'aberto',
  statusNota: 'PROMOVIDO a Bib Gourmand na edição MICHELIN Doha 2026 (vinha da categoria Selected).',
  cozinha: 'Contemporânea europeia',
  categorias: ['internacional', 'alta-acessivel'],
  destaque: 'BIB GOURMAND · promovido em 2026',
  local: 'Mina District (Old Doha Port)',
  bairro: 'Mina District',
  lat: 25.2745, lng: 51.5455,
  mapsQuery: 'Baron restaurant Mina District Doha',
  distKm: 3.5, tempoMin: 10,
  precoQar: [150, 280],
  precoNota: 'nao-confirmado',
  degustacao: null, brunch: null, almoco: { desc: 'Não confirmado', qar: null },
  alcool: null,
  reserva: 'recomendavel',
  ambiente: ['casual-sofisticado', 'porto', 'colorido'],
  vista: 'Mina District — o antigo porto repintado em cores, à beira-mar',
  rede: 'local',
  notas: { gastro: 8.5, autent: 5.0, custo: 8.5, doha: 7.5 },
  pratos: [
    { nome: 'Carta contemporânea europeia', qar: null, porque: 'Não há pratos específicos publicados; a promoção a Bib Gourmand em 2026 é o sinal de qualidade.' }
  ],
  porque: 'Vale por dois motivos: subiu no MICHELIN este ano e fica no Mina District — o porto velho reformado, um dos passeios mais bonitos e menos turísticos de Doha, a 10 minutos do Souq. Bom para combinar passeio + jantar leve.',
  tel: null, site: null, reservaUrl: null,
  fontes: [F.michelin26, { t: 'The Peninsula Qatar — MICHELIN Doha 2026', u: 'https://thepeninsulaqatar.com/article/10/12/2025/one-new-star-shines-in-michelin-guide-dohas-second-edition' }]
},

/* ============================================================
   5. FECHADOS / DUVIDOSOS
   ============================================================ */
{
  id: 'cut',
  nome: 'CUT by Wolfgang Puck',
  status: 'fechado',
  statusNota: 'FECHADO. Encerrou no Mondrian Doha em 31 de dezembro de 2022, ao fim do contrato de cinco anos. A festa de despedida ("The Last Dance") foi no réveillon de 2022/2023. Qualquer lista que ainda o inclua está desatualizada.',
  cozinha: 'Steakhouse americana',
  categorias: ['internacional'],
  local: 'Era no Mondrian Doha',
  bairro: 'West Bay Lagoon',
  lat: 25.3640, lng: 51.5250,
  mapsQuery: 'Mondrian Doha',
  distKm: 14, tempoMin: 20,
  precoQar: null, precoNota: 'nao-confirmado',
  degustacao: null, brunch: null, almoco: null,
  alcool: null, reserva: 'nao',
  ambiente: [], vista: null, rede: 'internacional',
  notas: { gastro: null, autent: null, custo: null, doha: null },
  pratos: [],
  porque: 'Não existe mais. Risque da lista.',
  tel: null, site: null, reservaUrl: null,
  fontes: [{ t: 'Hotelier Middle East — CUT fecha no Mondrian Doha', u: 'https://www.hoteliermiddleeast.com/food-beverage/cut-by-wolfgang-puck-closing-mondrian-doha' }, { t: 'Hotel & Catering — The Last Dance at CUT', u: 'https://hotelandcatering.com/festive-season/its-time-for-the-last-dance-at-cut-by-wolfgang-puck-mondrian-doha' }]
},
{
  id: 'scalini',
  nome: 'Scalini Doha',
  status: 'inconclusivo',
  statusNota: 'CONFLITO DE FONTES, NÃO RESERVE SEM LIGAR. O Instagram oficial da casa exibe "CLOSED UNTIL FURTHER NOTICE". Ao mesmo tempo, a página da Marriott (St. Regis / Al Gassar Resort) segue publicada e há relato de refeição em janeiro de 2026. Leitura mais provável: fechamento posterior a esse relato, ou pausa prolongada. O Instagram do próprio restaurante é a fonte mais recente e específica — considero-a a mais confiável.',
  cozinha: 'Italiana',
  categorias: ['internacional'],
  local: 'Al Gassar Resort / The St. Regis Doha',
  bairro: 'West Bay Lagoon',
  lat: 25.3675, lng: 51.5295,
  mapsQuery: 'Scalini Doha',
  distKm: 13, tempoMin: 20,
  precoQar: null, precoNota: 'nao-confirmado',
  degustacao: null, brunch: null, almoco: null,
  alcool: true, reserva: 'obrigatoria',
  ambiente: [], vista: null, rede: 'internacional',
  notas: { gastro: null, autent: 3.0, custo: null, doha: 3.5 },
  pratos: [],
  porque: 'Não reserve. Mesmo que esteja aberto, é italiano de marca internacional a 20 minutos — a categoria mais dispensável da sua lista, e agora com risco de você chegar e encontrar a porta fechada. Se quiser italiano com estrela, o Alba resolve.',
  tel: null,
  site: 'https://www.scaliniqa.com/',
  reservaUrl: null,
  fontes: [{ t: 'Instagram oficial @scalinidoha', u: 'https://www.instagram.com/scalinidoha/' }, { t: 'Marriott — Scalini (St. Regis Doha)', u: 'https://www.marriott.com/en-us/dining/restaurant-bar/dohxr-the-st-regis-doha/6872011-scalini.mi' }, { t: 'Scalini Doha — site oficial', u: 'https://www.scaliniqa.com/' }]
},
{
  id: 'al-malqa',
  nome: 'Al Malqa',
  status: 'aberto',
  statusNota: 'Rede local em operação (Salwa Road, West Bay e outras). NÃO fica no Souq Waqif.',
  cozinha: 'Madhbi / mandi / grelhados árabes',
  categorias: ['arabe', 'local', 'barato'],
  local: 'Salwa Road e outras unidades',
  bairro: 'Salwa Road',
  lat: 25.2560, lng: 51.4740,
  mapsQuery: 'Al Malqa Restaurant Doha',
  distKm: 6, tempoMin: 14,
  precoQar: [30, 80],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Estimativa. Preços visíveis só em plataformas de delivery.',
  degustacao: null, brunch: null, almoco: { desc: 'Almoço e jantar', qar: null },
  alcool: false,
  reserva: 'nao',
  ambiente: ['casual', 'popular', 'delivery'],
  vista: null, rede: 'local',
  notas: { gastro: 7.0, autent: 8.5, custo: 9.5, doha: 5.5 },
  pratos: [
    { nome: 'Mutton seekh com kuboos', qar: null, porque: 'O campeão de vendas segundo as plataformas locais.' },
    { nome: 'Madhbi', qar: null, porque: 'Carne assada sobre pedra quente — a especialidade que dá nome à casa.' }
  ],
  porque: 'Honestamente: é comida boa e barata que serve ao morador de Doha, não ao visitante com 3 noites. Bandar Aden entrega a mesma categoria (mandi/cordeiro) dentro do Souq, a pé, com muito mais ambiente. Corte.',
  tel: null,
  site: 'https://almalqa.com/',
  reservaUrl: null,
  fontes: [{ t: 'Al Malqa — site oficial', u: 'https://almalqa.com/' }]
},
{
  id: 'chapati-karak',
  nome: 'Chapati & Karak',
  status: 'aberto',
  cozinha: 'Café / karak / lanches',
  categorias: ['cafe', 'local', 'barato', 'doce'],
  destaque: 'O melhor karak da cidade',
  local: 'Katara Cultural Village (e outras unidades)',
  bairro: 'Katara',
  lat: 25.3595, lng: 51.5265,
  mapsQuery: 'Chapati and Karak Katara Doha',
  distKm: 12.5, tempoMin: 20,
  precoQar: [10, 40],
  precoNota: 'nao-confirmado',
  precoDetalhe: 'Estimativa de café/lanche. Sem tabela pública.',
  degustacao: null, brunch: null, almoco: { desc: 'Aberto o dia todo', qar: null },
  alcool: false, reserva: 'nao',
  ambiente: ['casual', 'ao ar livre', 'popular'],
  vista: 'Katara, junto à praia',
  rede: 'local',
  notas: { gastro: 7.5, autent: 9.5, custo: 10, doha: 8.0 },
  pratos: [
    { nome: 'Karak', qar: null, porque: 'Apontado por múltiplas fontes, incluindo Visit Qatar, como o melhor karak de Doha.' },
    { nome: 'Luqaimat', qar: null, porque: 'Uma das duas melhores luqaimat da cidade segundo as fontes locais (a outra é Shay Al Shomous).' },
    { nome: 'Chapati com queijo e ovo', qar: null, porque: 'O lanche que dá nome à casa.' }
  ],
  porque: 'Não é destino de jantar — é parada. Se você for a Katara (que vale a visita), pare aqui no fim da tarde. Karak + luqaimat por menos de R$ 50 a dois.',
  tel: null, site: null, reservaUrl: null,
  fontes: [{ t: 'Visit Qatar — street food', u: 'https://visitqatar.com/intl-en/things-to-do/get-inspired/street-food' }]
}
];
